### ISSUE TITLE
Ghost CLI does not seem to realize that my ghost instance is running

### ISSUE THREAD

**Issue by virtmann** [TryGhost/Ghost-CLI#461] opened 2017-08-22 20:32 UTC
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

Ghost CLI does not seem to realize that my ghost instance is running.  Running "ghost status" shows the instance as stopped when it is indeed running.

### Steps to Reproduce (for a bug report)

When running "ghost restart" I get an error that the Ghost instance is not currently running.  I can confirm that the ghost instance is running and working correctly.  If I try to run "ghost start" I get an error that the port is already in use (because ghost is running).

I am running Ghost 1.7.0 with Ghost-CLI 1.1.1.  I can confirm that Ghost 1.7.0 did work with Ghost-CLI 1.0.3

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Debug Information:
    Node Version: v6.11.2
    Ghost-CLI Version: 1.1.1
    Environment: production
    Command: 'ghost restart'
An error occurred.
Message: 'Ghost instance is not currently running.'

Stack: Error: Ghost instance is not currently running.
    at RestartCommand.run (/usr/lib/node_modules/ghost-cli/lib/commands/restart.js:9:35)
    at Function._run (/usr/lib/node_modules/ghost-cli/lib/command.js:198:48)
    at Object.handler (/usr/lib/node_modules/ghost-cli/lib/command.js:117:22)
    at Object.self.runCommand (/usr/lib/node_modules/ghost-cli/node_modules/yargs/lib/command.js:233:22)
    at Object.Yargs.self._parseArgs (/usr/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:990:30)
    at Object.Yargs.self.parse (/usr/lib/node_modules/ghost-cli/node_modules/yargs/yargs.js:532:23)
    at Object.run (/usr/lib/node_modules/ghost-cli/lib/bootstrap.js:165:14)
    at Object.<anonymous> (/usr/lib/node_modules/ghost-cli/bin/ghost:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04.3
* Node Version: 6.11.2
* Ghost-CLI Version: 1.1.1
* Environment: production
* Command: 'ghost restart'

**Comment by TomChantler** [comment] 2017-08-23 10:23
This is related to issue #431

**Comment by acburdine** [comment] 2017-08-23 10:39
@virtmann @TomChantler is correct in that it is likely a duplicate of #431 -> was there a server reboot at some point before running restart?

**Comment by virtmann** [comment] 2017-08-23 13:52
@TomChantler - Most likely, yes.  I have moved on and rebuilt the box cleanly with ghost-cli 1.1.1 and ghost 1.7.0.  I have not seen any issues yet after the rebuild.  I have the old VM still if there is anything you want me to test.

**Comment by triestpa** [comment] 2017-09-01 11:27
Is there a fix for this yet?  Ghost-CLI is broken on my server currently, it always shows that Ghost is stopped, even though Ghost is running.  The only way to reboot the process currently is using `ps aux | grep ghost` and manually killing the process, which then automatically reboots itself.

Migrating to a new server and doing a clean install fixes this, but causes my blog to lose all of it's Disqus comments, not that's not a great option for me currently.

**Comment by acburdine** [comment] 2017-09-01 11:37
@triestpa not yet - I will work on implementing the fix (which is outlined in #463) this weekend.

**Comment by gcochard** [comment] 2017-10-17 18:40
@triestpa A workaround is to add `"running": "<environment>"` to the `.ghost-cli` file in the ghost install directory, then it will once again query the process manager.

**Comment by hungys** [comment] 2017-10-27 07:42
Same issue here, and @gcochard 's workaround just works.

**Comment by skluthe** [comment] 2017-11-07 22:39
Is <environment> a variable I should be replacing? I added it to my file and had no luck.

**Comment by nsuchy** [comment] 2017-12-04 14:58
@skluthe I had the same issue I quite literally copied and pasted `"running": "<environment>"` into the file and restart worked fine.

**Comment by mheland** [comment] 2017-12-16 12:29
@gcochard confirmed, after a reboot on DigitalOcean VM the Ghost CLI does not find the running Ghost instance. Your fix works.

**Comment by AileenCGN** [comment] 2018-01-19 06:55
Closing this as it's a duplicate of #463 
@kirrg001 Please reopen, if I'm wrong here.

**Closed by AileenCGN** 2018-01-19 06:55 UTC
Labels: bug, needs info

**Comment by kirrg001** [comment] 2018-01-19 11:24
It's not really a duplicate. #463 is a summary of the referenced issues. This issue is already referenced in #463 (and some more). I think it's fine to close all issues which are referenced in #463 and leave a comment "covered by #463" or similar 👍

**Comment by aviral-verma** [comment] 2021-04-30 05:25
I faced a similar issue, but the problem in my case was that I mistakenly had a typo in the 'config.production.json' file. After correcting it the problem was solved.

**Comment by raulmar0** [comment] 2022-07-25 02:25
Hey there, just for any newbie that bumps to the same issue. I was having this problem but it was just because I was executing ghost-cli commands from another user
