### ISSUE TITLE
ghost restart fails with ECONNREFUSED 

### ISSUE THREAD

**Issue by FrankV01** [TryGhost/Ghost-CLI#673] opened 2018-03-17 22:26 UTC
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary
`ghost restart` and `ghost start` tends to fail (for `start` that's after a `stop`). 

### Steps to Reproduce (for a bug report)

1. Install ghost per the guidelines as documented (I started near ghost 1.0.x with the cli.)
2. update through time and releases. 
3. `ghost restart/start` mostly never worked for me. Sometimes a *server* restart fixes the problem but sometimes not. 

`ghost doctor` doesn't help. Despite the log file, the port is the one ghost is running on thus a restart should work. 

### Log file (for a bug report)

```
Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.5.2
    Environment: production
    Command: 'ghost restart'
Message: Ghost did not start.
Suggestion: journalctl -u ghost_theopensourceu-org -n 50
Stack: Error: Ghost did not start.
    at connectToGhostSocket.then.catch (/home/frankv/.npm-global/lib/node_modules/ghost-cli/lib/utils/port-polling.js:92:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Original Error Message:
Message: connect ECONNREFUSED 127.0.0.1:2368
Stack: Error: connect ECONNREFUSED 127.0.0.1:2368
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v16.04
* Node Version: Node Version: v8.10.0
* Ghost-CLI Version: 1.5.2
* Environment: production
* Command: `ghost restart`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in Slack & Docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by FrankV01** [comment] 2018-03-17 22:28
I want to add that I've received this error over the course of several versions. Every time I think it's fixed it reoccurs with the next update or what have. Usually fixing it is a matter of server restarts. I realize, that brings the server back up. The command still doesn't work properly for me.

**Comment by AileenCGN** [comment] 2018-03-19 11:11
Hey @FrankV01 

Sorry to hear that you're having trouble and thanks for the report!

To better understand and reproduce this issue, can you supply some more information?

- What are the tech specs of the server you're running (CPU, RAM)?
- Since which CLI version does this issue occur? Or was it always there?

**Comment by FrankV01** [comment] 2018-03-19 13:34
Hi @AileenCGN , 

Thank you for looking into this.  

* The server is a 1GB, 1 CPU VPS. 
* I'm afraid I don't recall the exact version and I don't believe it was always there. I updated periodically but less frequently then I updated Ghost itself.   The problem became very impact for me for the last two or three months.

**Comment by OllieCo** [comment] 2018-03-19 22:12
I am having the same issue. I am using Google Cloud with the following specs:

Machine type
n1-standard-1 (1 vCPU, 3.75 GB memory)

CPU platform
Intel Broadwell

Type
Standard persistent disk

Size
10 GB

Source image
ubuntu-1604-xenial-v20180306

**Comment by AileenCGN** [comment] 2018-03-20 11:03
Thanks for the information!!!! I will look into it next week and try to reproduce it, so we can give you a fix for this!

Also, @FrankV01 & @OllieCo we will probably release a new version of the CLI this week. Please update when it's out and post any updates here (did it appear again, was the error message more clear etc...). Thanks a lot!

**Comment by FrankV01** [comment] 2018-03-20 13:13
Thank you very much and @OllieCo , thank you for chiming in and confirming I'm not (too) crazy.

**Comment by kirrg001** [comment] 2018-03-21 07:30
@FrankV01 Did you already share the output of `journalctl -u ghost_theopensourceu-org -n 50`?

**Comment by FrankV01** [comment] 2018-03-21 13:23
I apologize, I didn't capture it. I'll reproduce tonight (US) and post both.

**Comment by AileenCGN** [comment] 2018-03-22 04:28
Thanks! I will look into this next week.

I think, this might also be related to #639

**Comment by kirrg001** [comment] 2018-03-22 08:53
@AileenCGN I think it would be very useful to pipe the output of journalctl if Ghost won't start. If have the feeling that people don't run the journalctl command. The output will tell you why Ghost didn't start.

**Comment by FrankV01** [comment] 2018-03-22 21:51
@AileenCGN , yes -- that issue is close to (if not) the same thing. It always occurred after updates which is when I needed to do restarts. The update restart would fail and then I would manually try to restart (or start).

Finally, regarding reproducing the error, **I couldn't**. 

* First, I tried a `ghost restart` and it restarted cleanly. 
* Second, I did the upgrade (to v1.21.6) and the update when off without a hiccup. 👍 

(It's possible the first restart helped the update go smoothly but I doubt that is the case)

I attempted to execute other restarts, just to see if the error would occur and it never did. So either the team fixed it at some point or I changed something (though I don't know what that might be).

I'll leave it to you and your team on whether to close the issue. 

@kirrg001 - I did do the `journalctl` but failed to include it in the issue or save the output. The error message was the title of this issue. I know, though, that the details before the error are what you need. I'll remember to save it next time. Maybe autosaving or showing it would be helpful though.

**Comment by FrankV01** [comment] 2018-03-22 21:53
I tried it from tmux, too, in case that had an issue (which I usually use). Again, it restarted fine. I think the issue is resolved.

**Closed** 2018-03-22 22:15 UTC
Labels: recommended-stack

**Comment by OllieCo** [comment] 2018-03-22 22:19
It appears to have solved my issue too 👍 🥇

**Comment by helloitse** [comment] 2019-01-05 09:01
I am having this issue!

After running: journalctl -u ghost_enoma-co -n 50
```
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.

```
And after running: sudo journalctl -u ghost_enoma-co -n 50
```
-- Logs begin at Sat 2019-01-05 07:05:46 UTC, end at Sat 2019-01-05 08:58:23 UTC. --
Jan 05 08:48:16 ghenom systemd[1]: Started Ghost systemd service for blog: enoma-co.
Jan 05 08:48:20 ghenom systemd[1]: Stopping Ghost systemd service for blog: enoma-co...
Jan 05 08:48:21 ghenom node[6019]: /usr/local/lib/node_modules/ghost-cli/lib/process-manager.js:58
Jan 05 08:48:21 ghenom node[6019]:         throw error;
Jan 05 08:48:21 ghenom node[6019]:         ^
Jan 05 08:48:21 ghenom node[6019]: [object Object]
Jan 05 08:48:21 ghenom systemd[1]: ghost_enoma-co.service: Main process exited, code=exited, status=1/FAILURE
Jan 05 08:48:21 ghenom systemd[1]: ghost_enoma-co.service: Failed with result 'exit-code'.
Jan 05 08:48:21 ghenom systemd[1]: Stopped Ghost systemd service for blog: enoma-co.
```

Any thoughts?

**Comment by kirrg001** [comment] 2019-01-05 11:18
@helloitse Maybe this issue helps? https://github.com/TryGhost/Ghost-CLI/issues/701
Otherwise, please our [forum](https://forum.ghost.org) for questions/help 👍
