### ISSUE TITLE
Nginx is not installed. Skipping Nginx setup. but i have install nginx.

### ISSUE THREAD

**Issue by scccy** [TryGhost/Ghost-CLI#1531] opened 2021-08-11 06:32 UTC
### Steps to Reproduce
i want to set SSL
so,i do this
1. ghost set nginx
![image](https://user-images.githubusercontent.com/29171795/128980141-0c3138be-f516-4a39-a3db-51efa7d71f06.png)
2. nginx -V
![image](https://user-images.githubusercontent.com/29171795/128980211-749fa16b-423f-4b81-b55d-ce39dcb1478e.png)
how can ghost find nginx right

* OS: cnetos8 
* Node Version:14.17.4
* Ghost-CLI Version: 1.17.3
* Ghost version: 4.11.0 
* Environment:test

**Comment by calvingit** [comment] 2021-12-06 06:24
Me too.

**Comment by mxkris** [comment] 2021-12-21 21:01
Same issue here.

**Comment by ErisDS** [comment] 2022-01-20 15:56
Closing as a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/460

**Closed by ErisDS** 2022-01-20 15:56 UTC
