### ISSUE TITLE
Cannot install using `no-setup-linux-user` (and nvm)

### ISSUE THREAD

**Issue by SparkyDoosan** [TryGhost/Ghost-CLI#437] opened 2017-08-11 13:11 UTC
### This issue is a

* [ x] Bug Report
* [ ] Feature Request

### Summary

Ghost install (local or production) fails with error "→ id: ghost: No such user".

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost install local --no-setup-linux-user -V'

$ nvm ls
->      v6.11.1
         system
node -> stable (-> v6.11.1) (default)
stable -> 6.11 (-> v6.11.1) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> v6.11.1)
lts/argon -> v4.8.4 (-> N/A)
lts/boron -> v6.11.1

### Steps to Reproduce (for a bug report)

1. In a fresh directory, issue `ghost install local --no-setup-linux-user -V`
2. Wait, observe the following:

(multiple log lines that look OK, followed on the console by)
✔ Configuring Ghost
[05:53:00] Setting up instance [started]
[05:53:00] Setting up instance [completed]
[05:53:00] Running database migrations [started]
[05:53:00] Running database migrations [failed]
[05:53:00] → id: ghost: No such user

The debug log:

Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.3
    Environment: development
    Command: 'ghost install local --no-setup-linux-user -V'
Error occurred running command: 'undefined'

* OS: Linux pantheon 3.2.63-grsec #1 SMP Fri Oct 24 13:43:09 PDT 2014 i686 AMD Athlon(tm) 64 X2 Dual Core Processor 4600+ AuthenticAMD GNU/Linux
 
* Node Version: 6.11.1
* Ghost-CLI Version: 1.0.3
* Environment: dev
* Command: ghost install local --no-setup-linux-user -V

THANKS

**Comment by acburdine** [comment] 2017-08-11 13:16
Closing as a duplicate of #400 - a fix will be released in the next version.

**Closed by acburdine** 2017-08-11 13:16 UTC
