### ISSUE TITLE
 Cannot find module 'node_sqlite3.node' on install

### ISSUE THREAD

**Issue by regalstreak** [TryGhost/Ghost-CLI#353] opened 2017-07-12 17:09 UTC
### This issue is *sadly* a

* [ x ] Bug Report
* [ ] Feature Request

### Summary

If this is a bug, double-check and make sure there's not already an existing issue for it, then provide a quick summary of what error is occurring.

If this is a feature request, use this section to describe what feature you would like to see in the CLI, as well as a quick summary of any benefits or drawbacks you can think of if this feature is implemented.

### Steps to Reproduce (for a bug report)

1. Just install it the way ive done in attached log

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu LTS 16.04.1
* Node Version: v6.11.1
* Ghost-CLI Version: 1.0.0-rc.2
* Command: ```ghost install --url=https://vaae.sh --db=sqlite3 --dbpath=./content/data/ghost.db```

```
root@vaae:/var/www/ghost# ghost install --url=https://vaae.sh --db=sqlite3 --dbpath=./content/data/ghost.db
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking operating system
ℹ Checking MySQL is installed [skipped]
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v1.0.0-rc.1
✔ Finishing install process
✔ Configuring Ghost
✔ Setting up instance
Running sudo command: chown -R ghost:ghost /var/www/ghost/content
✔ Setting up "ghost" system user
? Do you wish to set up Nginx? Yes
✔ Creating nginx config file at /var/www/ghost/system/files/vaae.sh.conf
Running sudo command: ln -sf /var/www/ghost/system/files/vaae.sh.conf /etc/nginx/sites-available/vaae.sh.conf
Running sudo command: ln -sf /etc/nginx/sites-available/vaae.sh.conf /etc/nginx/sites-enabled/vaae.sh.conf
Running sudo command: service nginx restart
✔ Setting up Nginx
? Do you wish to set up SSL? Yes
? Enter your email (used for Let's Encrypt notifications) regalstreak@gmail.com
Running sudo command: service nginx restart
✔ Creating ssl parameters file at /var/www/ghost/system/files/ssl-params.conf
Running sudo command: service nginx restart
✔ Setting up SSL
? Do you wish to set up automatic SSL renewal? Yes
✔ Setting up automatic SSL renewal
? Do you wish to set up Systemd? Yes
✔ Creating systemd service file at /var/www/ghost/system/files/ghost_vaae-sh.service
Running sudo command: ln -sf /var/www/ghost/system/files/ghost_vaae-sh.service /lib/systemd/system/ghost_vaae-sh.service
Running sudo command: systemctl daemon-reload
✔ Setting up Systemd
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/lib/node_modules/ghost-cli/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ghost-cli/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client_SQLite3._driver (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
root@vaae:/var/www/ghost# 
```

gg

**Comment by acburdine** [comment] 2017-07-12 17:10
Closing this as a duplicate of #281

**Closed by acburdine** 2017-07-12 17:10 UTC
