### ISSUE TITLE
Ghost process exited with code: 0

### ISSUE THREAD

**Issue by tiborsaas** [TryGhost/Ghost-CLI#698] opened 2018-04-07 21:23 UTC
https://github.com/TryGhost/Ghost-cli#recommended-stack.

## This issue is a

* [x] Bug Report
* [ ] Feature Request

Please fill out this template, deleting where appropriate:

### Summary

I updated the ghost-cli and now I can't start my ghost blog.

    Debug Information:
        Node Version: v8.0.0
        Ghost-CLI Version: 1.1.3
        Environment: production
        Command: 'ghost start'

### Steps to Reproduce (for a bug report)

1. run `ghost start` :)

### Technical details (for a bug report)
![image](https://user-images.githubusercontent.com/342688/38460478-b9c63638-3aba-11e8-972e-4df7f92bad83.png)

* OS: Ubuntu 14.04.1 LTS

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment] 2018-04-07 22:02
@tiborsaas It looks like you're on an older version of the CLI - would you mind upgrading and see if that fixes your issue? (You're on 1.1.3, while the latest CLI version is 1.6).

Going to close this issue as a duplicate of #501 - if updating to the latest CLI version doesn't fix your issue please comment again and we can reopen this 😄

**Closed by acburdine** 2018-04-07 22:02 UTC

**Comment by tiborsaas** [comment] 2018-04-08 00:47
Not sure why it listed the previous one, now I logged back in and the issue is gone. However I get now that I have too little memory available :(

**Comment by tiborsaas** [comment] 2018-04-08 00:53
![image](https://user-images.githubusercontent.com/342688/38461729-fc82cb40-3ad7-11e8-969c-b91e076d7f21.png)
