### ISSUE TITLE
Ghost Problem with SSL

### ISSUE THREAD

**Issue by Cavain** [TryGhost/Ghost-CLI#671] opened 2018-03-14 18:24 UTC
Hello,

I Installed Ghost on my cPanel server but now i am facing issue with SSL. I found so many articles describing SSL setup with nginx but it won't work for me. I have SSL installed in my domain but when i open my domain without SSL , like " http://domain.com " it works and when i try to open it with SSL Like this " https://domain.com " It shows all the home direcotrys instead of Ghost platform.

`[root@server public_html]# sudo systemctl status ghost
● ghost.service
   Loaded: loaded (/etc/systemd/system/ghost.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-03-14 18:15:41 CET; 1h 16min ago
  Process: 15109 ExecStop=/usr/bin/npm stop --production (code=exited, status=1/FAILURE)
 Main PID: 15987 (npm)
   CGroup: /system.slice/ghost.service
           ├─15987 npm
           └─16002 node index
`

Website link " tonsio.com " 

Thanks

**Comment by acburdine** [comment] 2018-03-14 21:20
@Cavain Setting up Ghost using cPanel isn't supported - there are a lot of "gotchas" that you'll run into unfortunately. However, the issue that it looks like you're running into is that the SSL config for nginx (or apache, whichever one you're using), isn't proxying the requests to Ghost.

If you're using nginx, there should be a particular block in your non-ssl configuration (since you said non-https works) that looks like this:
```
location / {
  proxy_pass http://localhost:2368;
  # additional fields here
}
```

if you copy that same config to your ssl config, then it should start working. Going to close this as I'm fairly certain it's a configuration issue and not a bug in Ghost-CLI. If it _does_ turn out to be a bug in Ghost-CLI we can reopen this.

**Closed by acburdine** 2018-03-14 21:20 UTC
