### ISSUE TITLE
Http errorcode 502 after system reboot

### ISSUE THREAD

**Issue by chanssl** [TryGhost/Ghost-CLI#212] opened 2017-06-16 11:45 UTC
Debian 8
Ghost-CLI version: 1.0.0-alpha.18
nginx version: 1.10.3

>ghost ls
![image](https://user-images.githubusercontent.com/4261299/27225219-c5b5de6c-52cb-11e7-902b-3682ffd9eff7.png)

Seems to have started, but  could not access the blog site (502 Bad Gateway) , need to restart the ghost.

**Comment by acburdine** [comment] 2017-06-16 11:47
I would try `ghost restart`. Something that hasn't been set up yet is "enabling" of the systemd service that allows it to be restarted whenever the system is rebooted.

**Comment by acburdine** [comment] 2017-06-17 00:21
I'm actually going to close this as a duplicate of #207 now that I think about it - that issue addresses the solution to this problem.

**Closed by acburdine** 2017-06-17 00:21 UTC

**Comment by chanssl** [comment] 2017-06-17 06:25
@acburdine OK
