### ISSUE TITLE
Sqlite corruption after 3.18.1 update

### ISSUE THREAD

**Issue by tobiasboyd** [TryGhost/Ghost-CLI#1213] opened 2020-06-03 18:08 UTC
### Issue Summary

I'm seeing `ghost update` fail trying to bump from 3.17.1 to 3.18.1, something in the migrations seems to munge our sqlite db. The update offers to roll back to 3.17.1 but that doesn't work, as the db is left in a unusable state. 

### To Reproduce

`cd /var/www/ghost && ghost update`

The intial error message after that suggested running `journalctl -u ghost_ideas-rejuvenation-com -n 50` (should say to that with sudo?) which returns

![Screen Shot 2020-06-03 at 11 05 22 AM](https://user-images.githubusercontent.com/1182465/83671810-23a04f80-a58a-11ea-82a4-b04ca494b35a.png)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Ghost Version: 3.17.1
* Node Version: 12.18.0
* Browser/OS: Ubuntu 16.04
* Database: sqlite

**Comment by vikaspotluri123** [comment] 2020-06-03 18:26
This _should_ be fixed in https://github.com/TryGhost/Ghost-CLI/commit/3f07b05a63cbaa94dd02a26b66a83901e0bdab3c, though I'm still trying to wrap my head around why it decided to break with this specific update 🤔

**Comment by tobiasboyd** [comment] 2020-06-03 18:37
I rolled my server back to a known-good backup, so I will stay tuned for when it ships. Thanks for all your hard work!

**Comment by ErisDS** [comment] 2020-06-03 19:04
Sorry, I moved the issue and then got distracted before I finished writing a comment.

This is caused by having a relative path in your config. The workaround is to change the path to your sqlite DB to be absolute in your config as seen here: https://forum.ghost.org/t/unable-to-upgrade-ghost-from-v3-16-1-to-v3-18-0/14836/5

I'm gonna close this now as it's fixed in master by https://github.com/TryGhost/Ghost-CLI/commit/3f07b05a63cbaa94dd02a26b66a83901e0bdab3c, but thanks for the nicely written report :)

**Closed by ErisDS** 2020-06-03 19:04 UTC

**Comment by tobiasboyd** [comment] 2020-06-03 19:19
That worked perfectly, thanks @ErisDS ! (I assume that's future-proof, and when the changes in https://github.com/TryGhost/Ghost-CLI/commit/3f07b05a63cbaa94dd02a26b66a83901e0bdab3c ship everything will keep working?)

**Comment by acburdine** [comment] 2020-06-03 19:23
@tobiasboyd the changes in that commit actually convert relative sqlite paths to be absolute, so you'd essentially be manually applying the changes 😄

**Comment by acburdine** [comment] 2020-06-07 20:53
The fix in https://github.com/TryGhost/Ghost-CLI/commit/3f07b05a63cbaa94dd02a26b66a83901e0bdab3c was released as part of Ghost-CLI 1.14.1  😄
