### ISSUE TITLE
 Error: Cannot find module './build/Release/DTraceProviderBindings': Ghost 1.0 on FreeBSD 11

### ISSUE THREAD

**Issue by neelchauhan** [TryGhost/Ghost-CLI#379] opened 2017-07-23 01:04 UTC
### Issue Summary

When I run Ghost 1.0 on FreeBSD 11.0, I get this error:

    An error occurred.
    Message: 'Command failed: knex-migrator-migrate --init --mgpath /root/gh/current
    { Error: Cannot find module './build/Release/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/default/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    { Error: Cannot find module './build/Debug/DTraceProviderBindings'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
    
    null'

This error happens on my server and on my desktop, both running FreeBSD 11.0, and happens on both MySQL and SQLite modes.

### Steps to Reproduce

1. Have a FreeBSD box ready
2. Run `pkg install node6` and then `pkg install npm3`
3. Run `npm install ghost-cli`
4. Make a new directory, and execute `ghost install`
5. Follow the steps, except with saying no to systemd and nginx
6. Try to run Ghost by running (GHOST_DIR)/current/index.js
7. You get this error

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected it to start Ghost like it did on the 0.11.x versions, but instead got this error.

### Technical details:

* Ghost Version: 1.0
* Node Version: 6.10.1
* Browser/OS: FreeBSD 11.0 amd64
* Database: SQLite (but MySQL also had this error)

**Comment by MaximusMcCann** [comment] 2017-07-27 02:46
Similar on my mac.  Have tried uninstalling and reinstalling ghost-cli and such.

```
Error: Module version mismatch. Expected 48, got 51.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
✔ Checking for latest Ghost version
✔ Running system checks
✔ Setting up install directory
✔ Downloading and installing Ghost v1.0.0
✔ Moving files
✔ Configuring Ghost
ℹ Running setup checks [skipped]
✔ Setting up instance
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/usr/local/lib/node_modules/ghost-cli/node_modules/sqlite3/lib/binding/node-v48-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client_SQLite3._driver (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:75:12)
    at Client_SQLite3.initializeDriver (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:219:26)
    at Client_SQLite3.Client (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:113:10)
    at new Client_SQLite3 (/usr/local/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:58:20)
### Steps to Reproduce (for a bug report)
```

**Comment by max302** [comment] 2017-07-27 02:55
This is likely a problem with DTrace. Many other node apps will throw dtrace errors but run regardless, I've had this problem with Storj. Apparently this is a problem with dtrace provider support in BSD. Here is a link discussing this: [http://darksi.de/7.freebsd-dtrace/](http://darksi.de/7.freebsd-dtrace/)

I am having the same problem as OP, and can confirm that 1.0.0b4 installed and ran just fine when installed locally through `ghost install local`. I do remember seeing Dtrace exceptions having been thrown around the install process, but as in the other apps that I have had this with, they did not stop the application from working correctly. 

1.0.0 will start my backed up beta 4 install just fine. When creating a new site, install finishes with dtrace errors, upon starting I get the following message:
``` Debug Information:
    Node Version: v6.11.0
    Ghost-CLI Version: 1.0.0
    Environment: development
    Command: 'ghost start'
Message: An error occurred.
Stack: Error: An error occurred.
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:55:35)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:758:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) ```

Same kind of config on my end, FreeBSD 11.0 / Node LTS / latest ghost installed from npm.

**Comment by acburdine** [comment] 2017-07-27 13:16
From what it looks like, the dtrace errors are not the actual problem here.

@neelchauhan, your issue shows dtrace warnings, yes, but the problem itself looks like a duplicate of #378.

@MaximusMcCann, your issue looks like #281, please see that issue for steps to resolve it.

@max302, not quite sure what your issue is, but running `ghost run` in your blog directory should show you what the problem is. If the problem turns out not to be an already open issue, please open a new one 😄 

Going to close this issue though as the problems shown are not Dtrace errors; rather, they are individually separate errors that already have open issues.

**Closed by acburdine** 2017-07-27 13:16 UTC
Labels: bug
