### ISSUE TITLE
Can't get a local install with `ghost install local`

### ISSUE THREAD

**Issue by emolchanov** [TryGhost/Ghost-CLI#104] opened 2016-12-05 18:20 UTC
I get no errors, but process is active very long time without error logs and crashes.

![ghost install local 2016-12-05 20-12-28](https://cloud.githubusercontent.com/assets/2001429/20896815/22893e2c-bb28-11e6-818f-72c0816c52e1.png)
![htop 2016-12-05 20-13-30](https://cloud.githubusercontent.com/assets/2001429/20896816/22c43fa4-bb28-11e6-94ac-da3246cca665.png)

**Comment by acburdine** [comment] 2016-12-08 02:17
@emolchanov Based on what you've shown, I'm not entirely sure what error is occurring, but it appears that the `npm install ghost` command is hanging up on one of its dependencies. I'm going to take a look later at changing from npm over to yarn, so we'll see if that helps at all.

Would you be willing/able to provide a better description of your environment so I can further help debug this?

**Comment by emolchanov** [comment] 2016-12-09 13:50
@acburdine sure :) What do you need?

**Comment by ecwyne** [comment] 2017-01-16 18:48
I am having the exact same issue. Literally left it running overnight to no avail. Happy to help in any way I can

**Comment by acburdine** [comment] 2017-01-16 18:59
@ecwyne sorry you're having trouble as well!

Can both of you update to 1.0.0-alpha.9 (of the CLI, just published it) and see if that solves the issue with `ghost install local`?

If that doesn't fix the issue, I'm planning on refactoring the CLI tool to use Yarn here soon, so it should make it a little more stable wrt the installation process.

**Comment by ecwyne** [comment] 2017-01-16 20:06
@acburdine thanks for the rapid response!

Just updated to 1.0.0-alpha.9 and still seems to get stuck at the same place.
`Downloading and installing Ghost v1.0.0-alpha.9`

**Comment by acburdine** [comment] 2017-01-28 21:34
@emolchanov @ecwyne I just released a new version of the CLI (1.0.0-alpha.10) - can you try that and let me know if the issue is fixed?

The new version uses Yarn rather than npm - so you'll need to install Yarn first 😄 Fortunately though - it should improve reliability of things tremendously.

**Comment by ecwyne** [comment] 2017-01-28 21:45
<img width="824" alt="screen shot 2017-01-28 at 1 45 19 pm" src="https://cloud.githubusercontent.com/assets/5205440/22400063/0b195972-e560-11e6-9311-e6486e4d0711.png">

**Comment by acburdine** [comment] 2017-01-28 21:48
@ecwyne so - the issue there is that Ghost by default tries to run on a system stack that is Ubuntu 16, nginx, and systemd-based. The problem you're getting is because you're trying to run this on a mac.

In the next version, there will be more strides given to ensure that ^ error doesn't occur, and the process manager falls back to the local one, but for the moment just run `ghost install local` instead.

(Also, that was the original title of the issue, so if `ghost install local` works now then I'll close this 😉)

**Comment by ecwyne** [comment] 2017-01-28 21:50
I actually realized that I ran `ghost i` without `local` so I started that right after I sent that picture. It's starting up now. Install went MUCH faster thanks to yarn caching! 😄

**Comment by ecwyne** [comment] 2017-01-28 21:54
Not sure how long "`Starting Ghost`" should take, but it's looked like this for maybe 5 mins.
<img width="393" alt="screen shot 2017-01-28 at 1 53 27 pm" src="https://cloud.githubusercontent.com/assets/5205440/22400110/44510aa4-e561-11e6-9359-3dd4e92daffd.png">

**Comment by ecwyne** [comment] 2017-01-28 22:40
After leaving this running for 30 minutes it still was saying "Starting Ghost"

I then
1. Stopped the process
2. Ran `ghost config`
3. Ran `ghost run` 

<img width="1128" alt="screen shot 2017-01-28 at 2 40 03 pm" src="https://cloud.githubusercontent.com/assets/5205440/22400373/b05d5efe-e567-11e6-8b2c-7267effdc56e.png">

**Comment by acburdine** [comment] 2017-01-28 22:44
@ecwyne try running `ghost run -D` ghost install local uses the development NODE_ENV, so if you want to use the config created for a local setup you have to run Ghost in development as well.

**Comment by ecwyne** [comment] 2017-01-28 22:57
I WAS able to start the server when I ran `ghost run -D` though I still get lots of `Error: Cannot find module './build/Release/DTraceProviderBindings'` errors

I cleared the directory and started over again one more time, got stuck at `Starting Ghost` but then checked if `localhost:2368` was working and it WAS.

**Comment by acburdine** [comment] 2017-01-29 01:09
Hmm...ok - would you be willing to hop on the ghost slack channel here? https://slack.ghost.org
We can chat in real time there.

Ping me once you're on (username: austin) and we can hopefully get this resolved quicker :)

**Comment by acburdine** [comment] 2017-01-30 19:21
I'm actually fairly certain that the bug that caused this issue initially is the same bug that caused the second issue - this should be fixed in #139

**Closed** 2017-01-30 19:31 UTC
Labels: bug

**Comment by acburdine** [comment] 2017-02-06 19:03
@emolchanov @ecwyne Released this fix with Ghost-CLI 1.0.0-alpha.11 - please let me know if you have further issues 😄

**Comment by emolchanov** [comment] 2017-02-13 14:44
With Ghost-CLI 1.0.0-alpha.11 all is ok 👍 thx

**Comment by emolchanov** [comment] 2017-02-13 15:07
@acburdine but after install, if I stop ghost with `ghost stop` and try to start it again with `ghost start` I have an error on macOs Sierra.

![image](https://cloud.githubusercontent.com/assets/2001429/22888565/e1b4b4b2-f20e-11e6-9d2c-1aebce5ff549.png)

**Comment by acburdine** [comment] 2017-02-13 15:29
@emolchanov So if you installed with `ghost install local` - you'll need to start it with `ghost start -D`, because `ghost start` by default tries to start Ghost in the production environment.

I'll do some messaging improvements this week too to try and improve the UI around this, but as a workaround `ghost start -D` will work 😄

**Comment by emolchanov** [comment] 2017-02-13 20:17
@acburdine ok, thanks.
