### ISSUE TITLE
ghost start/stop doesn't work after computer power off (without ghost stop)

### ISSUE THREAD

**Issue by acko-kolosek** [TryGhost/Ghost-CLI#240] opened 2017-06-27 13:20 UTC
When I shutdown my computer, without stopping ghost instance, next time I start my PC, it won't let me to start ghost, saying that ghost is already running (which is not), and won't let me stop it because searched process id doesn't exist (in worse case it would kill some non-linked process, just my presumption, didn't happened yet). So I found solution, to remove .ghostpid file and then stop would work, and start again would work. It would be handy if this problem was fixed, so that automation of this process doesn't depend on removing .ghostpid file

**Comment by ErisDS** [comment] 2017-06-27 13:24
Thanks for raising this, I thought this was covered by #216 but then forgot to check when reviewing this morning.

**Comment by acburdine** [comment] 2017-06-27 13:31
Hey - going to close this as a duplicate of #207 :) Once that issue is fixed this problem shouldn't happen.

**Closed by acburdine** 2017-06-27 13:31 UTC
Labels: rogue

**Comment by acburdine** [comment] 2017-06-27 13:37
This is also related to #241

**Comment by acburdine** [comment] 2017-06-27 21:58
@acko-kolosek sorry for asking for more info after closing this - what OS are you running on?

**Comment by acko-kolosek** [comment] 2017-07-04 11:11
@acburdine sorry for response delay, Ubuntu 16.04 currently
