### ISSUE TITLE
Upgrade failure - unclear and unclean handling

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/Ghost-CLI#726] opened 2018-05-23 13:37 UTC
I've been upgrading a bunch of Ghost CLI managed blogs today. Most of the upgrades went fine, but one of them encountered a network error with npm. This will happen from time to time, and should be handled cleanly.

Instead, what happened next resulted in the blog being taken offline, which is totally not what I would have expected.

### Steps to Reproduce (for a bug report)

This is not really reproducible without faking a connection error, but here's what happened:

1. I ran `ghost update` everything was happy green ticks until...

```
✖ Downloading and updating Ghost to v1.23.0
A ProcessError occurred.

Message: Command failed: yarn install --no-emoji --no-progress
warning ghost@1.23.0: The engine "cli" appears to be invalid.
error An unexpected error occurred: "https://registry.yarnpkg.com/@tryghost/extract-zip/-/extract-zip-1.6.6.tgz: ESOCKETTIMEDOUT".

yarn install v1.6.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/var/www/ghost/versions/1.23.0/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Exit code: 1
```
(no additional output in logs)

2. I re-ran `ghost doctor`, just to be absolutely certain. All green.

3. I re-ran `ghost update`

```
✔ Checking for latest Ghost version
ℹ Downloading and updating Ghost [skipped]
Running sudo command: systemctl is-active ghost_mysite
Running sudo command: systemctl stop ghost_mysite
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
✖ Running database migrations
A ProcessError occurred.

Message: The database migration in Ghost encountered an error.
Help: https://docs.ghost.org/v1/docs/troubleshooting#section-general-update-error
Suggestion: ghost update --rollback
```

From the log file:

```
--------------- stderr ---------------
sudo: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate: command not found
```

The blog then went offline until I ran the rollback command.

----

## Why this is a bug 

So what has happened is the dependencies failed to install, which can happen any time npm has a glitch. The update aborted but didn't clean up after itself.

The second update sees the new folder (which is broken) and tries to switch over the symlink.

The bug is two-fold: 
1. that the update fails but doesn't clean up after itself
2. that the second update thinks there is a working Ghost version where there is not

Additionally, this has 2 very bad side effects:
1. It takes a blog offline unexpectedly
2. It leaves the user in a state where, unless they have intimate knowledge of Ghost CLI, they are stuck and must seek help/support.

### Technical details (for a bug report)

Debug Information:
    OS: Ubuntu, v16.04
    Node Version: v8.9.1
    Ghost-CLI Version: 1.7.3
    Environment: production
    Command: 'ghost update'

**Comment by acburdine** [comment] 2018-05-23 14:07
Hmm, yeah I can definitely see where this would occur.

Here are my thoughts for getting a fix out for this:
1. Handle errors in ghost update & delete the newly installed version folder if install fails. This should hopefully be simple enough to implement, and should fix the majority of issues
2. Add another check to `ghost doctor`, run on update, that does its best to ensure the dependencies are installed correctly (maybe using `yarn check`? https://yarnpkg.com/en/docs/cli/check)
3. Implement #153 - which will start Ghost on another port to ensure it starts up correctly.

**Comment by kirrg001** [comment] 2018-07-20 21:04
@acburdine

**Comment by acburdine** [comment] 2018-07-21 15:18
So the cause of the original issue (namely a failed version install not cleaning up after itself) has been fixed as of Ghost-CLI 1.8.0. The reason I didn't close this issue yet is there were a couple of other improvements I wanted to make to the upgrade process that I haven't been able to make yet.

Would be fine with closing this issue in favor of #153 + opening up another issue for the `yarn check` thing.

**Comment by kirrg001** [comment] 2018-07-21 15:49
> Would be fine with closing this issue in favor of #153 

If we put the knex-migrators back into Ghost, this might might not work easily anymore 🤔Running migrations requires that either the blog is in maintenance mode (which 1.0 currently doesn't support) or the blog is stopped.

**Comment by kirrg001** [comment] 2018-07-21 15:50
> opening up another issue for the yarn check thing.

Agree

**Comment by acburdine** [comment] 2018-07-21 19:55
Gonna go ahead and close this issue in favor of #153 and #760, since the original cause of the issue has (for the most part) been remedied.

**Closed by acburdine** 2018-07-21 19:55 UTC
Labels: bug
