### ISSUE TITLE
Need to check for available disk space before doing ghost update

### ISSUE THREAD

**Issue by dsecareanu** [TryGhost/Ghost-CLI#1301] opened 2020-09-21 07:18 UTC
### Summary

When running ghost update, because ghost keeps a lot of files in various folders (i.e. lots of content .json files in content/data folder, going back even 2 years or 5 versions of itself for the rollback option) you do happen to run out of disk space on your virtual machine (my case was running 10 ghost blogs on a 30gb aws ec2, 7 of them with just demo content and no traffic, but all of them occupying 2-3gb disk space just because of some of the things mentioned above, mainly rollback versions).

In this particular instance I did run out of space when doing a ghost update, which caused weird error log messages (attached an archive for reference
[Archive.zip](https://github.com/TryGhost/Ghost-CLI/files/5253892/Archive.zip)
) and all ghost sites to be unable to start anymore (even if server restarted). Only one site wasn't updated and was still running, but next time I tried to update it (even though there was like 5gb free space on disk now), the result of that update was identical as with the other sites (which tells me the space issues caused smth in some of components of ghost).

Initially I thought it was a database corruption issue cause by the failed updates, but migrating the sites on another server and doing fresh installs + content overwrite + database restore from broken sites ghost eventually worked and sites were restored properly.

Anyways, the idea is that there is a need to check for existing disk space, in the same way in which ghost checks for available memory when doing a ghost update.

@acburdine said he will add an issue based on https://forum.ghost.org/t/issues-updating-ghost-due-to-insufficient-space/16627/15, but I think he forgot.

Thanks! :)

**Comment by vikaspotluri123** [comment] 2020-09-21 15:10
This was completed in #1284 😄 closing as a duplicate of #1282

**Closed by vikaspotluri123** 2020-09-21 15:10 UTC

**Comment by dsecareanu** [comment] 2020-09-21 15:12
Oh, ok. :) I didn't see any open issue (didn't see it in the latest updates) so I assumed it wasn't added maybe. Thanks!
