### ISSUE TITLE
Issue #678

### ISSUE THREAD

**Issue by Benio101** [TryGhost/Ghost-CLI#678] opened 2018-03-20 03:07 UTC
## This issue is a

* [x] Bug Report
* [ ] Feature Request

### Steps to Reproduce (for a bug report)

1. `ghost install`
```
Running sudo command: /var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
? Password [input is hidden]
```

At this point, I don't know, **What password** to enter?

- Docs does not says anything about this.
- No error at this point, especially no error log.

#### Running `knex-migrator-migrate`
```
NODE_ENV=/var/www/ghost/current/node_modules/.bin/knex-migrator-migrate
/var/www/ghost/current/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
```
Running above `knex-migrator-migrate` from hand works asap.

#### Installing `knex-migrator`
```
sudo npm install -g knex-migrator
```
Installing `knex-migrator` as shown above works, but leaves a warning:
```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.13.1"
```

## Bug submission checklist

- [ ] Tried to find help in Slack & Docs: **I do not agree with Slack's ToS**, checked Docs.
- [x] Checked for existing issues
- [ ] Attached log file: **No error log at this point of installation**
- [ ] Provided technical details incl. operating system: **Details are generated upon error, but no error log at this point of installation**

**Comment by AileenCGN** [comment] 2018-03-20 04:27
Hey @Benio101 

Please don't use GitHub for support. This is not a bug with the CLI, but normal UNIX system behaviour were you get asked for your sudo password, as the command is running as `sudo`.

I'm closing this as it's not a bug in the CLI.

**Closed by AileenCGN** 2018-03-20 04:27 UTC

**Comment by Benio101** [comment] 2018-03-20 04:37
It's obviously not a `sudo` password ask and I am not asking for support. I don't know if it's your ignorance or lack of basic knowledge, but it's clearly a cli bug, most likely in `/lib/tasks/migrate.js`.

**Comment by vikaspotluri123** [comment] 2018-03-20 04:45
FYI you're definitely breaking [rule 3](https://ghost.org/conduct/#community-goals) of the CoC

Because of other issues, when a sudo command is run, output is proxied through the CLI, so when the sudo password is requested, you don't get the usual command. There was intentional context (`running sudo command...`) to suggest the CLI was asking for the sudo password.

Your issue with installing knex-migrator isn't an issue with ghost, rather an issue with NPM and the way it handles installation (on what I'm presuming is node 8)

**Comment by Benio101** [comment] 2018-03-20 05:17
Falsely accusing someone being not respectful is a serious defamation.
That's shame you personally attack others in order to defend your lack of basic knowledge.

> Your issue with installing knex-migrator
My issue is not with installing `knex-migrator`, but running it from your cli.
My issue #678 is related, if not duplicate of issue #378, that was correctly marked as bug by less ignorant and more knowledgable ghost developers than you two.

I was respectful until now, but at this point you showed that you don't deserve any kind of respect.
At this point, I've lost the interest of ghost, so I've lost the interest in this bug report aswell.

No regards.

**Comment by AileenCGN** [comment] 2018-03-20 08:30
Alright....

1. 
> Falsely accusing someone being not respectful is a serious defamation.

Nobody accused you 'falsely' you clearly were not respectful:
> I don't know if it's your ignorance or lack of basic knowledge

2. 
> My issue is not with installing knex-migrator, but running it from your cli.

Your issue does neither have a title nor any other description. You were starting this issue with asking what the password is for, which is clearly a support question. This was listed as "1.", but never followed by a "2.".

3. 
With our issue template we ask you to supply information, which you didn't do. At no point whatsoever did you say which node version, OS, CLI, or Ghost version you're having issue with. Hence there is no way to reproduce what you are experiencing.

4. 
Support is only offered by the community in our [Slack](https://slack.ghost.org) community and not here on GitHub. We ask you to respect our project and the people that are contributing to it. If - after looking further into it and gathering more necessary information - it turns out to be an issue with the CLI, we can always reopen it again.
