### ISSUE TITLE
ghost install local error

### ISSUE THREAD

**Issue by aaronmoodie** [TryGhost/Ghost-CLI#824] opened 2018-09-10 00:33 UTC
I'm trying to install a local copy of ghost for theme development, but am not able to get it running. I keep hitting an error when Ghost tries to start. I've looked online for solutions to this issue, but haven't found anything helpful. 

```
➜  ghost nodenv global 8.9.0
➜  ghost ghost install local
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✔ Downloading and installing Ghost v2.1.1
✔ Finishing install process
✔ Configuring Ghost
✔ Setting up instance
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✖ Starting Ghost
A GhostError occurred.

Message: Ghost process exited with code: 0

Debug Information:
    OS: Mac OS X, v10.13.6
    Node Version: v8.9.0
    Ghost-CLI Version: 1.9.3
    Environment: development
    Command: 'ghost install local'
```

Below is what I'm seeing in the log file. 

```
Stack: Error: Ghost process exited with code: 0
    at ChildProcess.cp.on (/usr/local/lib/node_modules/ghost-cli/lib/utils/local-process.js:56:24)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [x] Attached log file
- [x] Provided technical details incl. operating system

**Comment by acburdine** [comment] 2018-09-10 00:36
Hmm...yeah unfortunately `ghost start` isn't giving much to go on 😕 . Would you be able to run `ghost run -D` and post the output?

**Comment by aaronmoodie** [comment] 2018-09-10 00:46
hey @acburdine sure thing. 

```
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/aaron/Dropbox/Development/Projects/ghost/versions/2.1.1/core/server/config/utils.js:3:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/aaron/Dropbox/Development/Projects/ghost/versions/2.1.1/core/server/config/index.js:5:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

**Comment by acburdine** [comment] 2018-09-10 00:48
That looks like something went wrong with the actual `yarn install` process 🤔 

Try this and see if it fixes it:
```sh
cd current
rm -rf node_modules
yarn install
```

**Comment by aaronmoodie** [comment] 2018-09-10 00:51
Still getting the same issue. I've tried removing and re-istalling the CLI, and also re-installing ghost 3-4 times as well.

**Comment by aaronmoodie** [comment] 2018-09-10 00:53
I'm getting a warning when doing `yarn install`

```
➜  ghost cd current/
➜  2.1.1 rm -rf node_modules
➜  2.1.1 yarn install
yarn install v1.9.4
[1/5] 🔍  Validating package.json...
warning ghost@2.1.1: The engine "cli" appears to be invalid.
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 📃  Building fresh packages...
✨  Done in 31.82s.
```

**Comment by acburdine** [comment] 2018-09-10 00:55
That warning is normal - the only thing I can think then to try is running `yarn cache clean` and then `yarn install`?

If that doesn't work, try this: `ghost install 2.1.0 --local`. I'm wondering if something didn't get messed up with the ghost 2.1.1 publish 🤔

**Comment by aaronmoodie** [comment] 2018-09-10 01:01
Thanks! running `yarn cache clean` did the trick! 👌

**Comment by acburdine** [comment] 2018-09-10 01:02
Awesome! (there's actually a `ghost buster` command that will run `yarn cache clean` for you as well 😁)

Going to close this since the issue is resolved.

**Closed by acburdine** 2018-09-10 01:02 UTC

**Comment by aaronmoodie** [comment] 2018-09-10 01:06
Just looked at the CLI help, and the `buster` command docs. Maybe a better description of what this does would help here. 
```
Commands:
  ghost buster                 Who ya gonna call?
```

**Comment by acburdine** [comment] 2018-09-10 01:08
Haha yeah - it was added more as a joke than anything 😄 I can update the description though.

**Comment by mmatijevic-uniri** [comment] 2020-02-02 19:52
ghost install local
✔ Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v3.4.0
An error occurred.
Message: 'Response code 401 (Unauthorized)'


Debug Information:
    OS: Ubuntu, v18.04.3 LTS
    Node Version: v12.10.0
    Ghost-CLI Version: 1.13.1
    Environment: development
    Command: 'ghost install local'

Does anyone have a problem with this???

**Comment by talhag3** [comment] 2020-11-26 11:13
Checking system Node.js version
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
✔ Checking for latest Ghost version
✔ Setting up install directory
✖ Downloading and installing Ghost v3.38.3
An error occurred.
Message: 'Response code 401 (Unauthorized)'


Debug Information:
    OS: Ubuntu, v20.04.1 LTS
    Node Version: v12.19.0
    Ghost-CLI Version: 1.15.2
    Environment: development
    Command: 'ghost install local'
