### ISSUE TITLE
Nginx detection

### ISSUE THREAD

**Issue by slavaGanzin** [TryGhost/Ghost-CLI#1582] opened 2021-11-14 17:44 UTC
### Issue Summary

Hello, I don't know how you detect nginx, but ghost doesn't detect it on my setup.

You probably can just make `which nginx` or `nginx -v` for that.

```bash 
$ uname -a


$ nginx -v
nginx version: nginx/1.20.1
```

Nice product, thanks for that.

### Steps to Reproduce

1. run `ghost install` on any non-debian based linux

### Ghost Version

Ghost-CLI version: 1.18.0 Ghost version: 4.22.1 

### Node.js Version

v16.13.0

### How did you install Ghost?

ghost install --db=sqlite3 

### Database type

SQLite3

### Browser & OS version

Linux x 5.13.12-arch1-1 TryGhost/Ghost#1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux

### Relevant log / error output

```shell
✔ Setting up "ghost" system user
Nginx is not installed. Skipping Nginx setup.
ℹ Setting up Nginx [skipped]
Nginx setup task was skipped, skipping SSL setup
ℹ Setting up SSL [skipped]
```

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment] 2021-11-22 14:51
I've moved this issue to Ghost-CLI as that is where the nginx detection lives. Ghost CLI is designed to work on our [recommended stack](https://ghost.org/docs/install/ubuntu/#prerequisites/), however we're open to PRs that make simple changes but allow for supporting more stacks.

**Comment by slavaGanzin** [comment] 2021-11-22 15:15
https://github.com/TryGhost/Ghost-CLI/blob/56f9b6fb6f9da881ccc5d9fc32ca4850d84d33d5/packages/ghost-cli/extensions/nginx/index.js#L16

https://media4.giphy.com/media/Od0QRnzwRBYmDU3eEO/giphy.gif?cid=ecf05e47kgji9y5mrfiuniec1z8u5qowhzhjvl2jfgy07hyg&rid=giphy.gif&ct=g

**Comment by ErisDS** [comment] 2022-01-20 16:00
Closing this a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/460

**Closed by ErisDS** 2022-01-20 16:00 UTC
Labels: help wanted, other-stack
