### ISSUE TITLE
Got `connect ECONNREFUSED` when `ghost install local` with no proxies

### ISSUE THREAD

**Issue by lemorage** [TryGhost/Ghost-CLI#1905] opened 2024-11-29 08:02 UTC
### Summary

Search GitHub for existing issues & check the docs: https://ghost.org/docs/faq/. If you're still stuck, please provide a quick summary of the problem, steps to reproduce, and full tech details including logs.

### Steps to Reproduce

1. `ghost install local`
```
✖ Checking for latest Ghost version
An error occurred.
Message: 'Cannot read properties of undefined (reading 'statusCode')'


Debug Information:
    OS: Fedora Linux, v40
    Node Version: v20.17.0
    Ghost-CLI Version: 1.26.1
    Environment: development
    Command: 'ghost install local'

Additional log info available in: /home/miao/.ghost/logs/ghost-cli-debug-2024-11-29T07_45_10_175Z.log

Try running ghost doctor to check your system for known issues.
```

2. after some exploration, I closed my proxy on my local.

3. do `ghost install local` again
```
✖ Checking for Ghost-CLI updates
An error occurred.
Message: 'connect ECONNREFUSED 127.0.0.1:7890'


Debug Information:
    OS: Fedora Linux, v40
    Node Version: v20.17.0
    Ghost-CLI Version: 1.26.1
    Environment: production
    Command: 'ghost install local'

Additional log info available in: /home/miao/.ghost/logs/ghost-cli-debug-2024-11-29T07_45_55_387Z.log

Try running ghost doctor to check your system for known issues.
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Log file

All errors end with "Additional log info available in: [filepath]".

Use the command `cat [filepath]` to read the log, then copy & paste the contents here:

The log when proxy was on:
```
miao@fedora:~/Downloads/ghost-app$ cat /home/miao/.ghost/logs/ghost-cli-debug-2024-11-29T07_45_10_175Z.log
Debug Information:
    OS: Fedora Linux, v40
    Node Version: v20.17.0
    Ghost-CLI Version: 1.26.1
    Environment: development
    Command: 'ghost install local'
An error occurred.
Message: 'Cannot read properties of undefined (reading 'statusCode')'

Stack: TypeError: Cannot read properties of undefined (reading 'statusCode')
    at packageJson (/usr/local/lib/node_modules/ghost-cli/node_modules/package-json/index.js:71:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.loadVersions (/usr/local/lib/node_modules/ghost-cli/lib/utils/version.js:15:24)
    at async resolveVersion (/usr/local/lib/node_modules/ghost-cli/lib/utils/version.js:133:26)
    at async Task.version [as task] (/usr/local/lib/node_modules/ghost-cli/lib/commands/install.js:121:31)
```

The log when proxy was off:
```
miao@fedora:~/Downloads/ghost-app$ cat /home/miao/.ghost/logs/ghost-cli-debug-2024-11-29T07_45_55_387Z.log
Debug Information:
    OS: Fedora Linux, v40
    Node Version: v20.17.0
    Ghost-CLI Version: 1.26.1
    Environment: production
    Command: 'ghost install local'
An error occurred.
Message: 'connect ECONNREFUSED 127.0.0.1:7890'

Stack: RequestError: connect ECONNREFUSED 127.0.0.1:7890
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/ghost-cli/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at origin.emit (/usr/local/lib/node_modules/ghost-cli/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at onerror (/usr/local/lib/node_modules/ghost-cli/node_modules/agent-base/dist/src/index.js:117:21)
    at callbackError (/usr/local/lib/node_modules/ghost-cli/node_modules/agent-base/dist/src/index.js:136:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Code: ECONNREFUSED
Path: /ghost-cli
 ```

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Fedora Linux v40
* Node Version: v20.17.0
* Ghost-CLI Version: 1.26.1
* Environment: development
* Command: `ghost install local`

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [X] Attached log file
- [X] Provided technical details incl. operating system

**Comment by acburdine** [comment] 2024-11-29 20:14
@lemorage this is a duplicate of #1899 and has been fixed in main, but I haven't released a new version of the CLI since I've merged that change. I'm hoping to get a release out later this weekend or next week.

**Closed by acburdine** 2024-11-29 20:14 UTC
