### ISSUE TITLE
local setup complains about directory permissions

### ISSUE THREAD

**Issue by mlewe** [TryGhost/Ghost-CLI#711] opened 2018-04-29 20:44 UTC
## This issue is a

* [X] Bug Report
* [ ] Feature Request

### Summary

Using ghost-cli for a local setup (`ghost install local`) fails to start ghost again because of directory permissions.

### Steps to Reproduce

1. `ghost install local` works, starts ghost
2. `ghost stop` works
3. `ghost start` fails with the permission error given below
4. `ghost start --no-setup-linux-user` ignores directory permissions, starts ghost as expected

```
$ ghost start
Found a development config but not a production config, running in development mode instead
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✖ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
One or more errors occurred.

1) SystemError

Message: The path /home/foobar/ is not readable by other users on the system.
This can cause issues with the CLI, please either make this directory readable by others or run `ghost install` in another location.

Debug Information:
    OS: Arch, vrolling
    Node Version: v6.14.1
    Ghost-CLI Version: 1.7.1
    Environment: development
    Command: 'ghost start'

Try running ghost doctor to check your system for known issues.

Please refer to https://docs.ghost.org/v1/docs/troubleshooting#section-cli-errors for troubleshooting.
```

### Technical details (for a bug report)

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

 * OS: Arch, vrolling
 * Node Version: v6.14.1
 * Ghost-CLI Version: 1.7.1
 * Environment: development
 * Command: 'ghost start'

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [X] Tried to find help in the forum & docs
- [X] Checked for existing issues
- [ ] Attached log file … no log file exists
- [X] Provided technical details incl. operating system

**Comment by AileenCGN** [comment] 2018-04-30 03:33
Hey @mlewe 👋 

Thanks for the bug report! I can confirm that on install, we pass this task, because the `local` argument [is given](https://github.com/TryGhost/Ghost-CLI/blob/master/lib/commands/doctor/checks/install-folder-permissions.js#L19). But for the commands `start` and `update` it's missing and we actually run this check. This is not correct, as we should pass it for local installs as well. I'll add a fix for this and it should be solved in the next release. In the meantime, you will have to use ne `--no-setup-linux-user` flag for `ghost update` and `ghost start` as a workaround.

**Closed** 2018-05-09 01:06 UTC
Labels: bug, recommended-stack

**Comment by AileenCGN** [comment] 2018-05-10 02:12
Hey @mlewe 

Can you update your CLI? This should be fixed now!

**Comment by mlewe** [comment] 2018-05-11 07:18
Yes, it's indeed fixed. :)

**Comment by glalonde** [comment] 2021-05-16 19:07
I'm seeing this same issue, also on arch. Same process of `ghost install local`, `ghost stop`, and then `ghost start` fails like this.
```
[glalonde@trochanter ghost_local]$ ghost start
Found a development config but not a production config, running in development mode instead
✖ Checking system Node.js version - found v14.17.0
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
One or more errors occurred.

1) SystemError

Message: The directory /home/glalonde/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.

Debug Information:
    OS: Arch, vrolling
    Node Version: v14.17.0
    Ghost Version: 4.4.0
    Ghost-CLI Version: 1.17.1
    Environment: development
    Command: 'ghost start'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```


`ghost start --no-setup-linux-user` does still work, however.

**Comment by acburdine** [comment] 2021-05-23 18:41
@glalonde yeah - this is definitely still a known issue 😕 we'll make sure to address it as part of some larger refactoring we're planning on in the CLI

**Comment by kzbikowski** [comment] 2021-07-02 09:17
@acburdine, is there a workaround until then?

**Comment by aanishacharyaa** [comment] 2022-06-20 16:46
this issue is still present :
One or more errors occurred.

1) SystemError

Message: The directory /home/ubuntu/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.

Debug Information:
    OS: Ubuntu, v22.04 LTS
    Node Version: v16.15.1
    Ghost Version: 5.2.3
    Ghost-CLI Version: 1.21.0
    Environment: production
    Command: 'ghost start'

the error occurred after I changed the node js version. After boot ghost did not start automatically so I started manually and this error occurred after I fixed the node error by manually changing the node path in startup script

**Comment by marian-oprisan** [comment] 2022-11-24 20:33
I hope this helps some of you.
My issue was ubuntu version. I was using 22.10 and kept getting into issues. As soon as I switched to ubuntu 20.04, everything worked as it should. I know that ubuntu 22.10 is not listed as supported, but my server was already set up with tat version.

**Comment by tomwarner13** [comment] 2023-01-24 01:39
I just encountered this exact same issue with what appears to be the latest version of Ghost-CLI running on Ubuntu. The workaround of using `ghost start --no-setup-linux-user` works fine, but obviously I'd rather not have to use a workaround. I'm not doing anything goofy or weird with users or permissions or anything -- just did a by-the-book install in a directory on my user account, as my user account.

Debug information in case it helps:

```Running in development mode

✖ Checking system Node.js version - found v18.13.0
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
One or more errors occurred.

1) SystemError

Message: The directory /home/tom/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.

Debug Information:
    OS: Ubuntu, v20.04.5 LTS
    Node Version: v18.13.0
    Ghost Version: 5.29.0
    Ghost-CLI Version: 1.24.0
    Environment: development
    Command: 'ghost start'```

**Comment by marian-oprisan** [comment] 2023-01-24 17:58
"Ghost-CLI will create a new system user and user-group called ghost during the installation process. The ghost user will be used to run your Ghost process in systemd . This means that Ghost will run with a user that has no system-wide permissions or a shell that can be used (similar to other services such as NGINX)."
Souce: https://ghost.org/docs/ghost-cli/#:~:text=Ghost%2DCLI%20will%20create%20a,other%20services%20such%20as%20NGINX).

I think you should check that the user and group were successfully created.

**Comment by tomwarner13** [comment] 2023-01-26 02:55
I'm not seeing that user on my system, so it does indeed sound like that is the issue -- I don't have the output of the install command anymore but if I remember correctly it looked like it finished fine and nothing had gone wrong, so it's possible it could use a warning (it's also possible there was a great big warning and I ignored it though)

**Comment by isaacgr** [comment] 2023-02-25 14:55
Still seeing this when running `ghost install`

```

Love open source? We’re hiring JavaScript Engineers to work on Ghost full-time.
https://careers.ghost.org



✖ Checking system Node.js version - found v16.19.0
✔ Checking current folder permissions
✔ Checking memory availability
✔ Checking free space
One or more errors occurred.

1) SystemError

Message: The directory /home/isaac/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.

Debug Information:
    OS: Ubuntu, v22.04.1 LTS
    Node Version: v16.19.0
    Ghost-CLI Version: 1.24.0
    Environment: production
    Command: 'ghost install'

Try running ghost doctor to check your system for known issues.

You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.
```

**Comment by asimuzzaman** [comment] 2023-04-07 10:05
It was supposed to get resolvd earlier but the "bug" still persists. When running `ghost start` after clean installation using `ghost install local` it shows:
```
Running in development mode

✖ Checking system Node.js version - found v16.13.0
ℹ Ensuring user is not logged in as ghost user [skipped]
ℹ Checking if logged in user is directory owner [skipped]
✔ Checking current folder permissions
✔ Validating config
✔ Checking memory availability
✔ Checking binary dependencies
One or more errors occurred.

1) SystemError

Message: The directory /home/username/ is not readable by other users on the system.
This can cause issues with the CLI, you must either make this directory readable by others or install node and Ghost-CLI in another location.

Debug Information:
    OS: Ubuntu, v22.04.2 LTS
    Node Version: v16.13.0
    Ghost Version: 5.42.1
    Ghost-CLI Version: 1.24.0
    Environment: development
    Command: 'ghost start'

Try running ghost doctor to check your system for known issues.

```

**Steps to reproduce:**

- Run `ghost install local`
- Run `ghost stop`
- Run `ghost start`

**Comment by circus2271** [comment] 2023-06-27 16:14
> ## This issue is a
> * [x]  Bug Report
> * [ ]  Feature Request
> 
> ### Summary
> Using ghost-cli for a local setup (`ghost install local`) fails to start ghost again because of directory permissions.
> 
> ### Steps to Reproduce
> 1. `ghost install local` works, starts ghost
> 2. `ghost stop` works
> 3. `ghost start` fails with the permission error given below
> 4. `ghost start --no-setup-linux-user` ignores directory permissions, starts ghost as expected
> 
> ```
> $ ghost start
> Found a development config but not a production config, running in development mode instead
> ℹ Ensuring user is not logged in as ghost user [skipped]
> ℹ Checking if logged in user is directory owner [skipped]
> ✖ Checking current folder permissions
> ✔ Validating config
> ✔ Checking memory availability
> One or more errors occurred.
> 
> 1) SystemError
> 
> Message: The path /home/foobar/ is not readable by other users on the system.
> This can cause issues with the CLI, please either make this directory readable by others or run `ghost install` in another location.

so if the path /home/foobar/ is not readable by other users on the system, so maybe making it readable will solve the issue

at least, it worked in my case:

my folder was called ubuntu22user (and its path was /home/ubuntu22user)
so I checked its read permissions by typing `ls -la /home | grep ubuntu22user` and get this output:
`drwxr-x--- 14 ubuntu22user ubuntu22user 4096 Jun 27 18:41 ubuntu22user`

so, it means that not everybody has read acces to this folder ([this article](https://linuxize.com/post/chmod-command-in-linux/) clarified this to me)

so I just granted everybody read access by typing:
`chmod 754 /home/ubuntu22user/` and it fixed the issue

**Comment by circus2271** [comment] 2023-06-27 16:21
a

**Comment by webbycrown** [comment] 2024-02-13 10:46
I fixed by below command.

chmod 754 /home/< user >

**Comment by bcye** [comment] 2024-11-09 15:41
The bug still persists on Ghost-CLI 1.26.1/Ghost 5.100.1

**Comment by vikaspotluri123** [comment] 2024-11-10 01:22
#1897 might fix this, I happened to run into it while working on another issue.

@acburdine I see a couple of logs from production; should we discourage (add a check) production installs in a home directory?
