### ISSUE TITLE
Ghost-CLI not recognizing Nginx

### ISSUE THREAD

**Issue by DrDinosaur** [TryGhost/Ghost-CLI#406] opened 2017-07-30 23:15 UTC
### This issue is a

* [X ] Bug Report
* [ ] Feature Request

### Summary

Ghost-CLI is not recognizing my Nginx that was compiled by source. 

### Steps to Reproduce (for a bug report)

1. Compile and install Nginx from source
2. Run "ghost setup nginx"

The tool should recognize this as Nginx being installed and proceed as normal. 

`drdinosaur@mainserver:/var/www/ghost$ sudo ghost setup nginx
Nginx is not installed. Skipping Nginx setup.
? Setting up Nginx [skipped]
drdinosaur@mainserver:/var/www/ghost$ sudo nginx -v
nginx version: nginx/1.12.1`

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04
* Node Version: v6.11.1
* Ghost-CLI Version: 1.0.1
* Environment: production
* Command: ghost setup nginx

**Comment by acburdine** [comment] 2017-07-31 12:00
Closing as a duplicate of #282

**Closed by acburdine** 2017-07-31 12:00 UTC
