### ISSUE TITLE
Unable to update from Ghost 1.0 to 1.0.2 - Failed to lookup view "error" in views directory "/var/www/ghost/views"

### ISSUE THREAD

**Issue by grantwinney** [TryGhost/Ghost-CLI#386] opened 2017-07-27 17:29 UTC
### This issue is a

* [x] Bug Report
* [ ] Feature Request

### Summary

I received the banner message saying 1.0.1 is available (even though 1.0.2 was available at the time). I'm running 1.0 self-hosted.

When I attempt to update ghost with `ghost update`, it *appears* to succeed.

```none
[grant@ghost-blog:/var/www/ghost$ ghost update
✔ Checking for latest Ghost version
ℹ Downloading and updating Ghost [skipped]
Running sudo command: systemctl stop ghost_grantwinney-com
[sudo] password for grant:
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: -E -u ghost /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-07-27 17:19:03] INFO Finished database migration!
✔ Running database migrations
✔ Validating config
Running sudo command: systemctl start ghost_grantwinney-com
✔ Restarting Ghost](url)
```

The "skipped" output above might be because I attempted this earlier today too, before `ghost update --rollback`.

After the above runs and ghost restarts, my site only shows this:

```none
Oops, seems there is an error in the error template.

Encountered the error:

Failed to lookup view "error" in views directory "/var/www/ghost/views"

whilst trying to render an error page for the error:

undefined
Failed to lookup view "error" in views directory "/var/www/ghost/views"
```

I can run `ghost update --rollback` to bring the site back up.

### Steps to Reproduce (for a bug report)

1. Have site running 1.0 and observe banner showing update available.
2. Run `ghost update` and after ghost restarts the site is broken.
3. Run `ghost update --rollback` brings the site back up, still as 1.0.

### Technical details (will be automatically output by Ghost-CLI if an error occurs):

* OS: Ubuntu 16.04.2 LTS
* Node Version: v6.11.1
* Ghost-CLI Version: 1.0.0
* Environment: 
* Command:

**Comment by grantwinney** [comment] 2017-07-27 17:33
If there's a log file somewhere, I can post the contents of that too.

I saw some logs in the `/var/www/ghost/content/logs` directory but I'm not sure if any of it'll be helpful.

**Comment by ErisDS** [comment] 2017-07-27 17:40
Ok - so the problem here is that Ghost is looking in `/var/www/ghost/views` instead of `/var/www/ghost/current/core/server/views`.

Which is interesting cos that path isn't even close - it's missing `/current/` (which is ghost-cli specific) AND `/core/server/` which is the path in Ghost itself.

 I don't know what would have changed between 1.0.0 and 1.0.2 to cause this 🤔

**Comment by ErisDS** [comment] 2017-07-27 17:41
@grantwinney wondering whats in your config file related to paths... could you share whenever you have a minute?

**Comment by acburdine** [comment] 2017-07-27 17:44
For what it's worth I tried this locally and couldn't reproduce.

- `ghost install 1.0.0 --no-setup --no-stack`
- `ghost setup --local`
- `ghost update`

I had no issues. Will try this later on a production box.

**Comment by ErisDS** [comment] 2017-07-27 18:02
I also couldn't reproduce locally.

**Comment by grantwinney** [comment] 2017-07-27 18:12
Sure, here's my `config.production.json` file (with some info blocked out). Or did you mean a different config file? I can post whatever, if there's a file in a different location you'd like to see.

```json
{
  "url": "https://grantwinney.com",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "mysql",
    "connection": {
      "host": "localhost",
      "user": "*********",
      "password": "**********",
      "database": "ghost_production"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/www/ghost/content"
  }
}
```

**Comment by acburdine** [comment] 2017-07-27 18:19
@grantwinney that's the right config file - I will test this in production later tonight and see if I can figure out what's going on 😄

**Comment by acburdine** [comment] 2017-07-29 21:45
Hmm... @grantwinney I couldn't reproduce this, even after doing an update --rollback and then `ghost update` again 😕 

Could you try updating to the latest version of Ghost (1.1.0) and see if you still have this issue?

**Comment by grantwinney** [comment] 2017-07-31 10:50
I ran ghost update and it saw the new version and installed it...

```none
grant@ghost-blog:/var/www/ghost$ ghost update
✔ Checking for latest Ghost version
✔ Downloading and updating Ghost to v1.1.0
Running sudo command: systemctl stop ghost_grantwinney-com
[sudo] password for grant:
✔ Stopping Ghost
✔ Linking latest Ghost and recording versions
Running sudo command: -E -u ghost /usr/lib/node_modules/ghost-cli/node_modules/.bin/knex-migrator-migrate --init --mgpath /var/www/ghost/current
[2017-07-31 10:46:47] INFO Finished database migration!
✔ Running database migrations
✔ Validating config
Running sudo command: systemctl start ghost_grantwinney-com
✔ Restarting Ghost
```

... but after restarting ghost, I get the same error in the browser.

```none
Oops, seems there is an error in the error template.

Encountered the error:

Failed to lookup view "error" in views directory "/var/www/ghost/views"

whilst trying to render an error page for the error:

undefined
Failed to lookup view "error" in views directory "/var/www/ghost/views"
```

**Comment by ErisDS** [comment] 2017-07-31 10:53
@grantwinney Hmmmm I have a guess at what is happening here.

I think there is an error happening on boot that is being disguised by Ghost.

If I had to guess what that error would be - I think it is gscan complaining about Disqus code in your theme.

To try to verify this can you do two things:

1. share your logs from /var/www/ghost/content/logs/ - the one called something_error.log
2. let me know if your active theme happens to have Disqus code in it that uses `{{id}}` ?

**Comment by grantwinney** [comment] 2017-07-31 11:45
@ErisDS - I did insert some code related to Disqus into the theme (in post.hbs), but it looks similar to the commented-out block of code that's in the post.hbs file by default.

```none
<div id="disqus_thread"></div>
<script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = {{post.id}}; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://grantwinney.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
```

Here are the log files too. They both included timestamps in them from today so I uploaded them both.

* [https___grantwinney_com_production.error.log.txt](https://github.com/TryGhost/Ghost-CLI/files/1187303/https___grantwinney_com_production.error.log.txt)
* [https___grantwinney_com_production.error.log.3.txt](https://github.com/TryGhost/Ghost-CLI/files/1187308/https___grantwinney_com_production.error.log.3.txt)

**Comment by ErisDS** [comment] 2017-07-31 11:56
Seems my guess is correct, here's the error that appears in your logs:

```
ERROR: Log/1872 on ghost-blog: The currently active theme "casper-grant" is invalid. (req.originalUrl=/what-is-a-git-alias-and-how-do-i-use-it/amp/, req.params={}, req.query={}, res.responseTime=44ms, err.id=960176b0-75dd-11e7-924c-8f65d4710f9e, err.domain=https://grantwinney.com, err.code=null, err.statusCode=500, err.level=critical)
    GET /what-is-a-git-alias-and-how-do-i-use-it/amp/ HTTP/1.1
    x-forwarded-for: 180.76.15.22
    x-forwarded-proto: https
    x-real-ip: 180.76.15.22
    host: grantwinney.com
    connection: close
    user-agent: Mozilla/5.0 (compatible; Baiduspider/2.0; +http://www.baidu.com/search/spider.html)
    accept-language: en-US
    accept: */*
    
    {}
    --
    HTTP/1.1 500 Internal Server Error
    --
    InternalServerError: The currently active theme "casper-grant" is invalid.
        at new InternalServerError (/var/www/ghost/versions/1.1.0/node_modules/ghost-ignition/lib/errors/index.js:71:23)
        at ensureActiveTheme (/var/www/ghost/versions/1.1.0/core/server/themes/middleware.js:28:21)
        at Layer.handle [as handle_request] (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:317:13)
        at /var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:335:12)
        at next (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:275:10)
        at servePublicFile (/var/www/ghost/versions/1.1.0/core/server/middleware/serve-public-file.js:47:13)
        at Layer.handle [as handle_request] (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:317:13)
        at /var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:335:12)
        at next (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:275:10)
        at servePublicFile (/var/www/ghost/versions/1.1.0/core/server/middleware/serve-public-file.js:47:13)
        at Layer.handle [as handle_request] (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:317:13)
        at /var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:335:12)
        at next (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:275:10)
        at servePublicFile (/var/www/ghost/versions/1.1.0/core/server/middleware/serve-public-file.js:47:13)
        at Layer.handle [as handle_request] (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/layer.js:95:5)
        at trim_prefix (/var/www/ghost/versions/1.1.0/node_modules/express/lib/router/index.js:317:13)
    --
    req.meta: {
      "requestId": "96012890-75dd-11e7-924c-8f65d4710f9e",
      "userId": null
    }
    --
    res._headers: {
      "x-powered-by": "Express",
      "cache-control": "no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0",
      "content-type": "text/html; charset=utf-8",
      "content-length": "370",
      "etag": "W/\"172-SlFfg3xfNpHQurULyGUCMtoCytQ\"",
      "vary": "Accept-Encoding"
    }
    --
    err.errorDetails: [
      {
        "fatal": true,
        "level": "error",
        "rule": "Replace <code>{{id}}</code> with <code>{{comment_id}}</code> in Disqus embeds.",
        "details": "The output of <code>{{id}}</code> has changed between Ghost LTS and 1.0.0. This results in Disqus comments not loading on Ghost 1.0.0 posts which were imported from Ghost LTS. To resolve this, we've added a new <code>{{comment_id}}</code> helper that will output the old ID for posts that have been imported from LTS, and the new ID for new posts. The Disqus embed must be updated from <code>this.page.identifier = 'ghost-{{id}}';</code> to <code>this.page.identifier = 'ghost-{{comment_id}}';</code> to ensure Disqus continues to work.",
        "failures": [
          {
            "ref": "post.hbs"
          }
        ],
        "code": "GS002-DISQUS-ID"
      }
    ]
```

I'm a bit confused because the snippet you shared actually won't trigger this error given the current implementation, however it certainly should. 

To get your blog working, you need to make the required change to your theme - use `comment_id` instead of `id`, otherwise your comments will disappear from your old posts. (OR if you're not using it, delete the commented out snippet).

I will investigate why the error is being hidden, and raise a bug in Ghost to get that resolved. I'll close this issue against the new one once it's open.

**Comment by grantwinney** [comment] 2017-07-31 12:17
@ErisDS I had previously forked Casper so I could make a few adjustments without having it get overwritten when I did an update - I didn't realize failing to update the theme could cause a problem, but I see now why it did. I'll be doubly careful about that in the future.

I've since merged the latest Casper changes from the last few days (commits 3993cbd, cd4e0e0, 2b2d6e6, 35e91ec) and the upgrade worked successfully. I'll fix my disqus code to match what you've recommended too. Thanks so much!! _(and thanks @acburdine too)_

**Comment by ErisDS** [comment] 2017-07-31 12:38
Hi @grantwinney, unfortunately you're suffering from early adoption syndrome 😝 . We found the issue with Disqus just before we went official with 1.0 (i.e. published a blog post). The fix (addition of `{{comment_id}}` and subsequent changes to Casper happened in Ghost 1.0.2 and Casper 2.0.1.

Really sorry that this impacted you. The people who caught on to Ghost 1.0 before it was announced may all bump into this, but hopefully we'll get the error message ironed out quickly so that you can at least see what the problem is!

**Comment by ErisDS** [comment] 2017-08-01 08:42
Closing in favour of:

https://github.com/TryGhost/Ghost/issues/8808
and
https://github.com/TryGhost/gscan/issues/79

**Closed by ErisDS** 2017-08-01 08:42 UTC
