### ISSUE TITLE
Fresh install - no tables are created except migrations and migrations_lock

### ISSUE THREAD

**Issue by sintezcs** [TryGhost/Ghost-CLI#936] opened 2019-05-28 13:01 UTC
### Issue Summary

After doing a fresh install of Ghost on Ubuntu 18.04 - no tables are created except `migrations` and `migrations_lock`. Ghost fails to start with an error about the migration lock.

### To Reproduce

1. Follow the official manual to install Ghost on Ubuntu
2. Ghost fails to start with a message:
```
Migration lock was never released or currently, a migration is running.
If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
```
3. Try executing `knex-migrator rollback`. It fails with the message:
```
NAME: InternalServerError
MESSAGE: Please provide a file named MigratorConfig.js in your project root.
```
4. Connect to MySQL and check the database. Ensure that your ghost database (`ghost_prod` in my case) is in place. Check the tables in the DB:
```
mysql> use ghost_prod; show tables;
+----------------------+
| Tables_in_ghost_prod |
+----------------------+
| migrations           |
| migrations_lock      |
+----------------------+
```
5. Remove all items from migrations_lock
```
mysql> delete from migrations_lock;
```
6. Try running `ghost setup migrate`. There is no output or errors.
7. Try running `ghost start`. See the same error from step 2

### Technical details:

* Ghost Version: 2.23.0
* Ghost CLI Version: 1.10.0
* Node Version: 8.10.0
* Browser/OS: Ubuntu 18.04
* Database: MySQL 5.7.22

**Comment by kevinansfield** [comment] 2019-05-28 14:44
@sintezcs it sounds like this may be a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/450? You may find that issue has additional info and details on the type of logs that are useful for debugging.

**Comment by acburdine** [comment] 2019-05-29 09:52
@sintezcs the reason `ghost setup migrate` doesn't do anything is that migrations were moved back into Ghost core in version 2.x, and thus that command only works for Ghost 1.x blogs. I can update some of the verbage to output a warning message perhaps.

As to why migrations are failing, I'm not sure unfortunately 😓 I tried to reproduce the issue, following the setup steps [here](https://docs.ghost.org/install/ubuntu/) and installing on Ubuntu 18.04, but had no issues.

If you have any additional information you can provide (did anything perhaps go wrong during setup?) that would be incredibly helpful in debugging the issue 😄

**Comment by sintezcs** [comment] 2019-05-29 10:33
@acburdine  @kevinansfield  thank you for your responses! I will try to do a clean install today, uninstalling everything and doing it for scratch. I'll let you know about the issues.

**Comment by ErisDS** [comment] 2019-05-30 01:35
@acburdine I also experienced this exact same issue the other day, when the instance wasn't being created. As soon as I solved that issue, this one went away.

FWIW, I did I think 4/5 installs that failed consistently. And then 3 that succeeded.

To anyone experiencing this issue `ghost uninstall`, followed by `ghost install --verbose` and providing us with the full output from the install would be very helpful. Try it a few times & see if it consistently fails.

**Comment by joshuajbouw** [comment] 2019-05-30 10:17
```[10:12:15] Checking for Ghost-CLI updates [started]
[10:12:15] Checking for Ghost-CLI updates [completed]
[10:12:15] Ensuring correct ~/.config folder ownership [started]
[10:12:15] Ensuring correct ~/.config folder ownership [completed]
[10:12:15] Checking system Node.js version [started]
[10:12:15] Checking system Node.js version [completed]
[10:12:15] Checking logged in user [started]
[10:12:15] Checking logged in user [completed]
[10:12:15] Checking current folder permissions [started]
[10:12:15] Checking current folder permissions [completed]
[10:12:15] Checking operating system compatibility [started]
[10:12:15] Checking systemd is installed [started]
[10:12:15] Checking nginx is installed [started]
[10:12:15] Checking systemd is installed [completed]
[10:12:15] Checking nginx is installed [completed]
[10:12:15] Checking operating system compatibility [completed]
[10:12:15] Checking for a MySQL installation [started]
[10:12:15] Checking for a MySQL installation [completed]
[10:12:15] Checking memory availability [started]
[10:12:15] Checking memory availability [completed]
[10:12:15] Checking for latest Ghost version [started]
[10:12:15] Checking for latest Ghost version [completed]
[10:12:15] Setting up install directory [started]
[10:12:15] Setting up install directory [completed]
[10:12:15] Downloading and installing Ghost [started]
[10:12:15] Downloading and installing Ghost v2.23.1 [title changed]
[10:12:15] Getting download information [started]
[10:12:15] Getting download information [completed]
[10:12:15] Downloading [started]
[10:12:16] Downloading [completed]
[10:12:16] Installing dependencies [started]
[10:12:16] → yarn install v1.15.2
[10:12:16] → [1/5] Validating package.json...
[10:12:16] → [2/5] Resolving packages...
[10:12:16] → [3/5] Fetching packages...
[10:12:17] → [4/5] Linking dependencies...
[10:12:19] → [5/5] Building fresh packages...
[10:12:22] → $ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
[10:12:22] → Done in 6.11s.
[10:12:22] Installing dependencies [completed]
[10:12:22] Downloading and installing Ghost v2.23.1 [completed]
[10:12:22] Finishing install process [started]
[10:12:22] Linking latest Ghost and recording versions [started]
[10:12:22] Linking latest Ghost and recording versions [completed]
[10:12:22] Linking latest Casper [started]
[10:12:22] Linking latest Casper [completed]
[10:12:22] Finishing install process [completed]
[10:12:22] Configuring Ghost [started]
? Enter your blog URL: https://joshuajbouw.com
? Enter your MySQL hostname: localhost
? Enter your MySQL username: root
? Enter your MySQL password: [hidden]
? Enter your Ghost database name: blog
[10:12:49] Configuring Ghost [completed]
[10:12:49] Setting up "ghost" system user [started]
[10:12:49] Creating "ghost" system user [started]
[10:12:49] Creating "ghost" system user [skipped]
[10:12:49] Giving "ghost" user ownership of the /content/ directory [started]
+ sudo chown -R ghost:ghost /var/www/ghost/content
[10:12:49] Giving "ghost" user ownership of the /content/ directory [completed]
[10:12:49] Setting up "ghost" system user [completed]
[10:12:49] Setting up "ghost" mysql user [started]
? Do you wish to set up "ghost" mysql user? Yes
[10:12:55] Connecting to database [started]
[10:12:55] Connecting to database [completed]
[10:12:55] Creating new MySQL user [started]
MySQL: running query > SET old_passwords = 0;
MySQL: successfully disabled old_password
MySQL: running query > SELECT PASSWORD('REMOVED') AS password;
MySQL: successfully created password hash.
MySQL: running query > CREATE USER 'ghost-56'@'localhost' IDENTIFIED WITH mysql_native_password AS 'REMOVED';
MySQL: successfully created new user ghost-56
[10:12:55] Creating new MySQL user [completed]
[10:12:55] Granting new user permissions [started]
MySQL: running query > GRANT ALL PRIVILEGES ON blog.* TO 'ghost-56'@'localhost';
MySQL: Successfully granted privileges for user "ghost-56"
MySQL: running query > FLUSH PRIVILEGES;
MySQL: flushed privileges
[10:12:55] Granting new user permissions [completed]
[10:12:55] Saving new config [started]
[10:12:55] Saving new config [completed]
[10:12:55] Setting up "ghost" mysql user [completed]
[10:12:55] Setting up Nginx [started]
? Would you like to view or edit the nginx config file? No, continue
✔ Creating nginx config file at /var/www/ghost/system/files/joshuajbouw.com.conf
+ sudo ln -sf /var/www/ghost/system/files/joshuajbouw.com.conf /etc/nginx/sites-available/joshuajbouw.com.conf
+ sudo ln -sf /etc/nginx/sites-available/joshuajbouw.com.conf /etc/nginx/sites-enabled/joshuajbouw.com.conf
+ sudo nginx -s reload
[10:13:52] Setting up Nginx [completed]
[10:13:52] Setting up SSL [started]
? Do you wish to set up SSL? Yes
[10:13:55] Checking DNS resolution [started]
[10:13:55] Checking DNS resolution [completed]
[10:13:55] Getting additional configuration [started]
? Enter your email (For SSL Certificate) dev@joshuajbouw.com
[10:14:02] Getting additional configuration [completed]
[10:14:02] Installing acme.sh [started]
[10:14:02] Installing acme.sh [skipped]
[10:14:02] → acme.sh is already installed
[10:14:02] Getting SSL Certificate from Let's Encrypt [started]
+ sudo /etc/letsencrypt/acme.sh --issue --home /etc/letsencrypt --domain joshuajbouw.com --webroot /var/www/ghost/system/nginx-root --reloadcmd "nginx -s reload" --accountemail dev@joshuajbouw.com
[10:14:03] Getting SSL Certificate from Let's Encrypt [completed]
[10:14:03] Generating Encryption Key (may take a few minutes) [started]
[10:14:03] Generating Encryption Key (may take a few minutes) [skipped]
[10:14:03] Generating SSL security headers [started]
[10:14:03] Generating SSL security headers [skipped]
[10:14:03] Generating SSL configuration [started]
? Would you like to view or edit the ssl config file? No, continue
✔ Creating ssl config file at /var/www/ghost/system/files/joshuajbouw.com-ssl.conf
+ sudo ln -sf /var/www/ghost/system/files/joshuajbouw.com-ssl.conf /etc/nginx/sites-available/joshuajbouw.com-ssl.conf
+ sudo ln -sf /etc/nginx/sites-available/joshuajbouw.com-ssl.conf /etc/nginx/sites-enabled/joshuajbouw.com-ssl.conf
[10:14:13] Generating SSL configuration [completed]
[10:14:13] Restarting Nginx [started]
+ sudo nginx -s reload
[10:14:13] Restarting Nginx [completed]
[10:14:13] Setting up SSL [completed]
[10:14:13] Setting up Systemd [started]
? Do you wish to set up Systemd? Yes
? Would you like to view or edit the systemd service file? No, continue
✔ Creating systemd service file at /var/www/ghost/system/files/ghost_undefined.service
+ sudo ln -sf /var/www/ghost/system/files/ghost_undefined.service /lib/systemd/system/ghost_undefined.service
+ sudo systemctl daemon-reload
[10:14:28] Setting up Systemd [completed]
? Do you want to start Ghost? Yes
+ sudo systemctl is-active ghost_undefined
[10:14:49] Ensuring user is not logged in as ghost user [started]
[10:14:49] Ensuring user is not logged in as ghost user [completed]
[10:14:49] Checking if logged in user is directory owner [started]
[10:14:49] Checking if logged in user is directory owner [completed]
[10:14:49] Checking current folder permissions [started]
[10:14:49] Checking current folder permissions [completed]
[10:14:49] Validating config [started]
+ sudo systemctl is-active ghost_undefined
[10:14:49] Validating config [completed]
[10:14:49] Checking folder permissions [started]
[10:14:49] Checking folder permissions [completed]
[10:14:49] Checking file permissions [started]
[10:14:49] Checking file permissions [completed]
[10:14:49] Checking content folder ownership [started]
[10:14:49] Checking content folder ownership [completed]
[10:14:49] Checking memory availability [started]
[10:14:49] Checking memory availability [completed]
+ sudo systemctl start ghost_undefined
+ sudo systemctl stop ghost_undefined
✖ Starting Ghost
A GhostError occurred.

Message: Migration lock was never released or currently a migration is running.
Help: If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
Suggestion: journalctl -u ghost_undefined -n 50
Stack: Error: Migration lock was never released or currently a migration is running.
    at Server.server.close (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by sintezcs** [comment] 2019-05-30 11:01
Here is my output. Looks identical.

```
ghostuser@ubuntu-2gb-hel1-1:/var/www/ghost$ ghost uninstall
WARNING: Running this command will delete all of your themes, images, data, any files related to this Ghost instance, and the contents of this folder!
There is no going back!
? Are you sure you want to do this? Yes
+ sudo systemctl is-active ghost_undefined
? Sudo Password [hidden]
+ sudo systemctl is-active ghost_undefined
+ sudo systemctl stop ghost_undefined
+ sudo systemctl is-enabled ghost_undefined
✔ Stopping Ghost
+ sudo rm -rf /var/www/ghost/content
✔ Removing content folder
+ sudo rm -f /etc/nginx/sites-available/blog.spb.host.conf
+ sudo rm -f /etc/nginx/sites-enabled/blog.spb.host.conf
+ sudo rm -f /etc/nginx/sites-available/blog.spb.host-ssl.conf
+ sudo rm -f /etc/nginx/sites-enabled/blog.spb.host-ssl.conf
+ sudo nginx -s reload
+ sudo rm /lib/systemd/system/ghost_undefined.service
✔ Removing related configuration
✔ Removing Ghost installation
ghostuser@ubuntu-2gb-hel1-1:/var/www/ghost$ ghost install --verbose
[12:56:20] Checking for Ghost-CLI updates [started]
[12:56:21] Checking for Ghost-CLI updates [completed]
[12:56:21] Checking system Node.js version [started]
[12:56:21] Checking system Node.js version [completed]
[12:56:21] Checking logged in user [started]
[12:56:21] Checking logged in user [completed]
[12:56:21] Checking current folder permissions [started]
[12:56:21] Checking current folder permissions [completed]
[12:56:21] Checking operating system compatibility [started]
[12:56:21] Checking systemd is installed [started]
[12:56:21] Checking nginx is installed [started]
[12:56:21] Checking systemd is installed [completed]
[12:56:21] Checking nginx is installed [completed]
[12:56:21] Checking operating system compatibility [completed]
[12:56:21] Checking for a MySQL installation [started]
[12:56:21] Checking for a MySQL installation [completed]
[12:56:21] Checking memory availability [started]
[12:56:21] Checking memory availability [completed]
[12:56:21] Checking for latest Ghost version [started]
[12:56:23] Checking for latest Ghost version [completed]
[12:56:23] Setting up install directory [started]
[12:56:23] Setting up install directory [completed]
[12:56:23] Downloading and installing Ghost [started]
[12:56:23] Downloading and installing Ghost v2.23.1 [title changed]
[12:56:23] Getting download information [started]
[12:56:23] Getting download information [completed]
[12:56:23] Downloading [started]
[12:56:24] Downloading [completed]
[12:56:24] Installing dependencies [started]
[12:56:25] → yarn install v1.15.2
[12:56:25] → [1/5] Validating package.json...
[12:56:25] → [2/5] Resolving packages...
[12:56:26] → [3/5] Fetching packages...
[12:56:28] → [4/5] Linking dependencies...
[12:56:37] → [5/5] Building fresh packages...
[12:56:45] → $ cpy node_modules/@tryghost/members-theme-bindings/build/members-theme-bindings.js core/server/public/
[12:56:46] → Done in 20.96s.
[12:56:46] Installing dependencies [completed]
[12:56:46] Downloading and installing Ghost v2.23.1 [completed]
[12:56:46] Finishing install process [started]
[12:56:46] Linking latest Ghost and recording versions [started]
[12:56:46] Linking latest Ghost and recording versions [completed]
[12:56:46] Linking latest Casper [started]
[12:56:46] Linking latest Casper [completed]
[12:56:46] Finishing install process [completed]
[12:56:46] Configuring Ghost [started]
? Enter your blog URL: https://blog.spb.host
? Enter your MySQL hostname: localhost
? Enter your MySQL username: root
? Enter your MySQL password: [hidden]
? Enter your Ghost database name: ghost_clean
[12:57:28] Configuring Ghost [completed]
[12:57:28] Setting up "ghost" system user [started]
[12:57:28] Creating "ghost" system user [started]
[12:57:28] Creating "ghost" system user [skipped]
[12:57:28] Giving "ghost" user ownership of the /content/ directory [started]
+ sudo chown -R ghost:ghost /var/www/ghost/content
[12:57:28] Giving "ghost" user ownership of the /content/ directory [completed]
[12:57:28] Setting up "ghost" system user [completed]
[12:57:28] Setting up "ghost" mysql user [started]
? Do you wish to set up "ghost" mysql user? Yes
[12:57:37] Connecting to database [started]
[12:57:38] Connecting to database [completed]
[12:57:38] Creating new MySQL user [started]
MySQL: running query > SET old_passwords = 0;
MySQL: successfully disabled old_password
MySQL: running query > SELECT PASSWORD('9OmS&:SBbnaOb,viu:`F') AS password;
MySQL: successfully created password hash.
MySQL: running query > CREATE USER 'ghost-430'@'localhost' IDENTIFIED WITH mysql_native_password AS '*9338D041EF5A85E718688EE2BC038F05BF168030';
MySQL: successfully created new user ghost-430
[12:57:38] Creating new MySQL user [completed]
[12:57:38] Granting new user permissions [started]
MySQL: running query > GRANT ALL PRIVILEGES ON ghost_clean.* TO 'ghost-430'@'localhost';
MySQL: Successfully granted privileges for user "ghost-430"
MySQL: running query > FLUSH PRIVILEGES;
MySQL: flushed privileges
[12:57:38] Granting new user permissions [completed]
[12:57:38] Saving new config [started]
[12:57:38] Saving new config [completed]
[12:57:38] Setting up "ghost" mysql user [completed]
[12:57:38] Setting up Nginx [started]
? Do you wish to set up Nginx? Yes
? Would you like to view or edit the nginx config file? No, continue
✔ Creating nginx config file at /var/www/ghost/system/files/blog.spb.host.conf
+ sudo ln -sf /var/www/ghost/system/files/blog.spb.host.conf /etc/nginx/sites-available/blog.spb.host.conf
+ sudo ln -sf /etc/nginx/sites-available/blog.spb.host.conf /etc/nginx/sites-enabled/blog.spb.host.conf
+ sudo nginx -s reload
[12:58:05] Setting up Nginx [completed]
[12:58:05] Setting up SSL [started]
? Do you wish to set up SSL? Yes
[12:58:08] Checking DNS resolution [started]
[12:58:08] Checking DNS resolution [completed]
[12:58:08] Getting additional configuration [started]
? Enter your email (For SSL Certificate) a@spb.host
[12:58:13] Getting additional configuration [completed]
[12:58:13] Installing acme.sh [started]
[12:58:13] Installing acme.sh [skipped]
[12:58:13] → acme.sh is already installed
[12:58:13] Getting SSL Certificate from Let's Encrypt [started]
+ sudo /etc/letsencrypt/acme.sh --issue --home /etc/letsencrypt --domain blog.spb.host --webroot /var/www/ghost/system/nginx-root --reloadcmd "nginx -s reload" --accountemail a@spb.host
[12:58:13] Getting SSL Certificate from Let's Encrypt [completed]
[12:58:13] Generating Encryption Key (may take a few minutes) [started]
[12:58:13] Generating Encryption Key (may take a few minutes) [skipped]
[12:58:13] Generating SSL security headers [started]
[12:58:13] Generating SSL security headers [skipped]
[12:58:13] Generating SSL configuration [started]
? Would you like to view or edit the ssl config file? No, continue
✔ Creating ssl config file at /var/www/ghost/system/files/blog.spb.host-ssl.conf
+ sudo ln -sf /var/www/ghost/system/files/blog.spb.host-ssl.conf /etc/nginx/sites-available/blog.spb.host-ssl.conf
+ sudo ln -sf /etc/nginx/sites-available/blog.spb.host-ssl.conf /etc/nginx/sites-enabled/blog.spb.host-ssl.conf
[12:58:17] Generating SSL configuration [completed]
[12:58:17] Restarting Nginx [started]
+ sudo nginx -s reload
[12:58:17] Restarting Nginx [completed]
[12:58:17] Setting up SSL [completed]
[12:58:17] Setting up Systemd [started]
? Do you wish to set up Systemd? Yes
? Would you like to view or edit the systemd service file? No, continue
✔ Creating systemd service file at /var/www/ghost/system/files/ghost_undefined.service
+ sudo ln -sf /var/www/ghost/system/files/ghost_undefined.service /lib/systemd/system/ghost_undefined.service
+ sudo systemctl daemon-reload
[12:58:23] Setting up Systemd [completed]
? Do you want to start Ghost? Yes
+ sudo systemctl is-active ghost_undefined
[12:58:26] Ensuring user is not logged in as ghost user [started]
[12:58:26] Ensuring user is not logged in as ghost user [completed]
[12:58:26] Checking if logged in user is directory owner [started]
[12:58:26] Checking if logged in user is directory owner [completed]
[12:58:26] Checking current folder permissions [started]
[12:58:26] Checking current folder permissions [completed]
[12:58:26] Validating config [started]
+ sudo systemctl is-active ghost_undefined
[12:58:26] Validating config [completed]
[12:58:26] Checking folder permissions [started]
[12:58:26] Checking folder permissions [completed]
[12:58:26] Checking file permissions [started]
[12:58:26] Checking file permissions [completed]
[12:58:26] Checking content folder ownership [started]
[12:58:26] Checking content folder ownership [completed]
[12:58:26] Checking memory availability [started]
[12:58:26] Checking memory availability [completed]
+ sudo systemctl start ghost_undefined
+ sudo systemctl stop ghost_undefined
✖ Starting Ghost
A GhostError occurred.

Message: Migration lock was never released or currently a migration is running.
Help: If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
Suggestion: journalctl -u ghost_undefined -n 50
Stack: Error: Migration lock was never released or currently a migration is running.
    at Server.server.close (/usr/local/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitCloseNT (net.js:1671:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v8.10.0
    Ghost-CLI Version: 1.10.0
    Environment: production
    Command: 'ghost install --verbose'

Additional log info available in: /home/ghostuser/.ghost/logs/ghost-cli-debug-2019-05-30T10_58_36_314Z.log

Try running ghost doctor to check your system for known issues.

You can always refer to https://docs.ghost.org/api/ghost-cli/ for troubleshooting.
```

**Comment by acburdine** [comment] 2019-05-30 11:23
@sintezcs @joshuajbouw thanks for the log outputs! I think I know _where_ the issue is now, though not _why_ it's occurring necessarily. Need to debug this a bit more, but will work on getting this fixed as quick as I can 😄

**Comment by joshuajbouw** [comment] 2019-05-30 11:30
Yeah I got stumped, uninstalled all dependencies and reinstalled, tried cleaning everything as much as possible, still couldn't get it to work lol.

**Comment by ErisDS** [comment] 2019-05-30 11:37
The thing that you might be missing cleaning up is the `~/.ghost/config` file. Removing this was what fixed the issue for me. 

It would be insanely helpful if you'd share the contents and permissions set on the file before removing it, and let us know if that does fix it for you.

I had the same issue, removing the file helped, but then we couldn't reproduce anymore and still aren't sure what the reproduction is. Something is definitely wrong, the second we figure it out we will fix it!

**Comment by joshuajbouw** [comment] 2019-05-30 12:08
permissions:
```
-rw-rw-r--  1 joshuajbouw joshuajbouw   86 May 30 10:07 config
drwxrwxr-x  2 joshuajbouw joshuajbouw 4096 May 30 10:14 logs
```

config:
```
{
  "instances": {
    "joshuajbouw-com": {
      "cwd": "/var/www/ghost"
    }
  }
}
```

latest log in logs folder:
```Debug Information:
    OS: Ubuntu, v18.04
    Node Version: v10.16.0
    Ghost-CLI Version: 1.10.0
    Environment: production
    Command: 'ghost install --verbose'
Message: Migration lock was never released or currently a migration is running.
Help: If you are sure no migration is running, check your data and if your database is in a broken state, you could run `knex-migrator rollback`.
Suggestion: journalctl -u ghost_undefined -n 50
Stack: Error: Migration lock was never released or currently a migration is running.
    at Server.server.close (/usr/lib/node_modules/ghost-cli/lib/utils/port-polling.js:38:28)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:198:13)
    at emitCloseNT (net.js:1618:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by acburdine** [comment] 2019-05-30 12:26
@joshuajbouw @sintezcs I've released a (hopeful) fix for this issue in Ghost-CLI 1.10.1. Please try it and let me know if it fixes your issue 😄 

Will leave this issue open for a bit in case the fix doesn't work.

**Comment by sintezcs** [comment] 2019-05-30 12:45
I've just figured out the issue. I created a user named "ghost" in the first step.. 🤦‍♂ 
After I removed it and used "ghostuser" instead, everything worked smoothly.

**Comment by joshuajbouw** [comment] 2019-05-30 12:47
There is a difference this time in `ghost install --verbose` being that `+ sudo systemctl start ghost_joshuajbouw-com` is no longer undefined.

Also with @sintezcs, I noticed that it `[12:44:15] Creating "ghost" system user [skipped]` going to try just exactly that.

**Comment by joshuajbouw** [comment] 2019-05-30 12:54
I can CONFIRM deleting `ghost` user fixed everything.

**Comment by acburdine** [comment] 2019-05-30 12:57
awesome - going to close this issue then 😄 Feel free to comment if the issue resurfaces & we can dig into it further.

**Closed by acburdine** 2019-05-30 12:57 UTC

**Comment by joshuajbouw** [comment] 2019-05-30 13:35
There certainly is something else that is going on that is a bit... Odd.

```joshuajbouw@yggdrasil:/var/www/ghost$ ghost ls
+ sudo systemctl is-active ghost_joshuajbouw-com
┌─────────────────┬────────────────┬─────────┬──────────────────────┬─────────────────────────┬──────┬─────────────────┐
│ Name            │ Location       │ Version │ Status               │ URL                     │ Port │ Process Manager │
├─────────────────┼────────────────┼─────────┼──────────────────────┼─────────────────────────┼──────┼─────────────────┤
│ joshuajbouw-com │ /var/www/ghost │ 2.23.1  │ running (production) │ https://joshuajbouw.com │ 2368 │ systemd         │
└─────────────────┴────────────────┴─────────┴──────────────────────┴─────────────────────────┴──────┴─────────────────┘
```

When I try to access the website ie. https://joshuajbouw.com/ghost or the local IP address with the port 2368, even 192.168.0.*:2368/ghost ... Website isn't loading. Nothing in the .ghost/logs either.

**Comment by chovy** [comment] 2021-02-11 08:19
did anyone figure this out?

**Comment by FatlumBehrami** [comment] 2022-03-18 10:12
This is still happening also on my environment, trying to do fresh install with Ghost image for Docker: 
- Local environment: Windows 10
- Docker ghost version 4.39.1, 4.39, 4, latest (https://hub.docker.com/_/ghost) 

This issue seems not to be completely solved, please consider reopening and providing support as it's not clear why it's happening on a fresh install with Docker.
