### ISSUE TITLE
fail to install ghost

### ISSUE THREAD

**Issue by chanssl** [TryGhost/Ghost-CLI#210] opened 2017-06-13 04:29 UTC
> npm install -g ghost-cli

       npm WARN deprecated debug@2.6.6: invalid release
       npm WARN deprecated yarn@0.23.4: It is recommended to install Yarn using the native installation method for your environment. See https://yarnpkg.com/en/docs/install
       npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
       npm WARN deprecated localhost.daplie.com-certificates@1.2.5: Moved to localhost.daplie.me-certificates
       /usr/bin/ghost -> /usr/lib/node_modules/ghost-cli/bin/ghost
       
       > dtrace-provider@0.8.3 install /usr/lib/node_modules/ghost-cli/node_modules/dtrace-provider
       > node scripts/install.js

> ghost  install
> cat ghost-cli-debug*.log

    Debug Information:
        Node Version: v6.11.0
        Ghost-CLI Version: 1.0.0-alpha.17
        Environment: production
        Command: 'ghost install'
    An error occurred.
    Message: 'Command failed: yarn install --no-emoji --no-progress
    yarn install v0.23.4
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...
    '

    Stack: Error: Command failed: yarn install --no-emoji --no-progress
    yarn install v0.23.4
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    [3/4] Linking dependencies...

        at Promise.all.then.arr (/usr/lib/node_modules/ghost-cli/node_modules/execa/index.js:210:11)
        at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by PaszaVonPomiot** [comment] 2017-06-13 15:05
@chanssl if you have standard stack try using documented way of installing ghost-cli

**Comment by chanssl** [comment] 2017-06-13 16:50
@PaszaVonPomiot Thanks. but the same problems after I use `yarn global add ghost-cli` to install Ghost-CLI

> ghost install


	✔ Checking for latest Ghost version
	 ✔ Running system checks
	 ✔ Setting up install directory
	 ❯ Downloading and installing Ghost v1.0.0-beta.1
	   ✔ Getting download information
	   ✔ Downloading
	   ✖ Installing dependencies
		 → [2/4] Fetching packages...
	   Moving files
	An error occurred.
	Message: 'Command failed: yarn install --no-emoji --no-progress
	yarn install v0.23.4
	[1/4] Resolving packages...
	[2/4] Fetching packages...
	'


	Debug Information:
		Node Version: v6.11.0
		Ghost-CLI Version: 1.0.0-alpha.17
		Environment: production
		Command: 'ghost install'
	(node:3788) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error occurred running command: 'yarn install --no-emoji --no-progress'

**Comment by acburdine** [comment] 2017-06-13 16:57
Hey @chanssl, thanks for the issue report!

I'm gonna close this though as I'm fairly certain it's a duplicate of #192

**Closed by acburdine** 2017-06-13 16:57 UTC

**Comment by chanssl** [comment] 2017-06-13 17:55
@acburdine I am sorry for created a duplicate issue.
