### ISSUE TITLE
Throws TypeError when installing using --db=sqlite3 flag

### ISSUE THREAD

**Issue by JoshTumath** [TryGhost/Ghost-CLI#349] opened 2017-07-11 23:08 UTC
### This issue is a
* [x] Bug Report
* [ ] Feature Request

### Summary
After setting up my server ready to install Ghost 1.0, I received a TypeError when I reached the 'Running database migrations' step.

### Steps to Reproduce

1. Run `ghost install --db=sqlite3` in a new directory
2. Enter a HTTPS URL for your blog when prompted
3. Answer the remaining prompts with default answers until the 'Running database migrations' step

### Technical details:

```Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.0-rc.2
    Environment: production
    Command: 'ghost install --db=sqlite3'
An error occurred.
Message: 'Argument 0 must be a string'

Stack: TypeError: Argument 0 must be a string
    at TypeError (native)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:99:16
    at Promise._execute (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireRawConnection (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/dialects/sqlite3/index.js:98:12)
    at Object.create (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:239:16)
    at Pool._createResource (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:354:17)
    at Pool.dispense [as _dispense] (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:314:10)
    at Pool.acquire (/usr/lib/node_modules/ghost-cli/node_modules/generic-pool/lib/generic-pool.js:436:8)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:289:19
    at Promise._execute (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/lib/node_modules/ghost-cli/node_modules/bluebird/js/release/promise.js:79:10)
    at Client_SQLite3.acquireConnection (/usr/lib/node_modules/ghost-cli/node_modules/knex/lib/client.js:280:12)
    at /usr/lib/node_modules/ghost-cli/node_modules/knex/lib/runner.js:208:30```

**Comment by yoonsikp** [comment] 2017-07-11 23:08
You need --db='sqlite3'

**Comment by JoshTumath** [comment] 2017-07-11 23:10
Yes, that is what I did. :)

**Comment by ErisDS** [comment] 2017-07-12 10:00
We have had 2 people report this issue today (another in slack).

The problem is that if you set --db=sqlite3 you must also pass --dbpath=/path/to/db

I _think_ there may be some thing missing in the docs, but all the places I found mention both, so it would be great to get some feedback on how this was missed.

Secondly, I think it makes sense to use the default sqlite3 path of /content/data/ghost.db if --db=sqlite3 is passed, and no --dbpath is provided.

**Comment by regalstreak** [comment] 2017-07-12 16:31
It was deleted from the docs or something. The line is missing today

**Comment by JoshTumath** [comment] 2017-07-12 17:34
> Secondly, I think it makes sense to use the default sqlite3 path of `/content/data/ghost.db` if `--db=sqlite3` is passed, and no `--dbpath` is provided.
I think that would be great; also if the CLI tool was able to create the ghost.db file for you if it doesn't exist in the place you've pointed at. I had to create the DB file outside of the directory that Ghost was to be set up, because you can only run `ghost install` if the directory is empty.

**Comment by acburdine** [comment] 2017-07-12 17:36
@JoshTumath Ghost-CLI is already able to do that - the PR linked to this issue fixes the problem with the default path 😄

**Comment by JoshTumath** [comment] 2017-07-12 17:51
@acburdine Awesome, thanks! However, when I do as you say and specify that path, I get the following error:

```
Debug Information:
    Node Version: v6.11.1
    Ghost-CLI Version: 1.0.0-rc.2
    Environment: production
    Command: 'ghost install --db sqlite3 --dbpath ./content/data/ghost.db'
An error occurred.
Message: 'SQLITE_CANTOPEN: unable to open database file'

Stack: Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)
Code: SQLITE_CANTOPEN
```

**Comment by acburdine** [comment] 2017-07-12 18:08
This is true, hadn't realized the implications of this particular permissions issue. A fix will be implemented for both problems in the next version

**Comment by kirrg001** [comment] 2017-07-12 19:39
I just double checked on https://docs.ghost.org/v1.0.0/docs/install#section-options.
The docs say that you have to use both parameters. As said, would be actually cool to detect that in the CLI 👍

**Comment by JoshTumath** [comment] 2017-07-13 23:49
> This is true, hadn't realized the implications of this particular permissions issue. A fix will be implemented for both problems in the next version

@acburdine What exactly is the cause of this performance issue? Do you know of a hotfix for this in the meantime? 😄

**Comment by acburdine** [comment] 2017-07-13 23:54
Not a performance issue - a permissions issue :) there's not a hotfix at the moment, but I'm working on a fix that will be released in the next version (early next week).

**Comment by JoshTumath** [comment] 2017-07-14 00:05
I don't know why I said performance. 😆 Awesome, thanks for responding.

**Comment by acburdine** [comment] 2017-07-14 01:57
Oops didn't mean for that commit to close this issue

**Closed** 2017-07-15 02:54 UTC
Labels: before 1.0.0, bug
