### ISSUE TITLE
MySQL install was not found or is stopped

### ISSUE THREAD

**Issue by yogeshbeniwal** [TryGhost/Ghost-CLI#1453] opened 2021-04-14 02:51 UTC
### Summary

ghost doctor command is giving below warning/error 

> ✔ Checking system Node.js version
> ✔ Checking logged in user
> ✔ Ensuring user is not logged in as ghost user
> ✔ Checking if logged in user is directory owner
> ✔ Checking current folder permissions
> ✔ Checking system compatibility
> Local MySQL install was not found or is stopped. You can ignore this if you are using a remote MySQL host.
> Alternatively you could:
> a) install/start MySQL locally
> b) run `ghost install --db=sqlite3` to use sqlite
> c) run `ghost install local` to get a development install using sqlite3.
> ? Continue anyway? Yes
> MySQL check skipped
> ! Checking for a MySQL installation [skipped]
> sudo systemctl is-active ghost_www-sitename-com
> ? Sudo Password [hidden]
> Instance is currently running
> ! Validating config [skipped]
> ✔ Checking folder permissions
> ✔ Checking file permissions
> ✔ Checking content folder ownership
> ✔ Checking memory availability
> ✔ Checking binary dependencies
> ✔ Checking free space
> 

### Steps to Reproduce

1. Upgrade Ghost, Ghost-CLI, Node to recommended v14 and NPM to latest version
2. Use ghost doctor 

Ghost is running in production mode and is running fine with ghost start. However ghost doctor is still throwing above MySQL install was not found or is stopped warning/error.

### Technical details

This is automatically output by Ghost-CLI if an error occurs, please copy & paste:

* OS: Ubuntu, v20.04.2 LTS
* Node Version: v14.16.1
* Ghost-CLI Version: 1.16.3
* Environment: production
* Command: ghost doctor

## Bug submission checklist

Please fill out this checklist to acknowledge that you followed the requirements to submit a bug report.

- [x] Tried to find help in the forum & docs
- [x] Checked for existing issues
- [ ] Attached log file
- [x] Provided technical details incl. operating system

**Comment by jingkang99** [comment] 2021-08-01 15:40
after looking into the code, I found the reason. it checks **service** mysql (must be this name, not which or version) running or not.
**service mysql status**

cd /etc/init.d/
ln -s mariadb mysql

it solves the issue.

**Comment by Catreina** [comment] 2021-12-05 05:22
I don't know if this will help anyone, but I went and modified the current ghost-cli/lib/commands/doctor/checks/mysql.js file on my own system (Ghost v4.25.1, fresh install, Ubuntu 20.04.3, Node v16.13.1, Ghost-CLI 1.18.1) to add a mariadb check after the mysql check.  It seemed to me to be the quickest and cleanest change to make a mariadb check work on Ubuntu 20.04.  I am not a programmer by any stretch, but it -does- work for me for now, so here you go:

this goes immediately after the "async function mysqlIsRunning()" code block:

async function mariadbIsRunning() {
    try {
        const services = await sysinfo.services('mariadb');
        return services.some(s => s.name === 'mariadb' && s.running);
    } catch (error) {
        return false;
    }
}

and this goes directly into the "async function mysqlCheck(ctx, task)" block. after the "if (await mysqlIsRunning())" block:

    if (await mariadbIsRunning()) {
        // MariaDB service found that is also running, so return (instead of mysql)
        return;
    }


This way when the mysql check fails, it checks for mariadb.  Only if that one ALSO fails will the "Local MySQL install was not found" show.  YMMV

**Comment by sunknudsen** [comment] 2022-01-12 20:57
Looks like issue can be traced back to https://github.com/TryGhost/Ghost-CLI/blob/56f9b6fb6f9da881ccc5d9fc32ca4850d84d33d5/packages/ghost-cli/lib/commands/doctor/checks/mysql.js#L10 and https://github.com/TryGhost/Ghost-CLI/blob/56f9b6fb6f9da881ccc5d9fc32ca4850d84d33d5/packages/ghost-cli/extensions/nginx/index.js#L271 always returning `running: false` on some operating systems such as Debian 11 "bullseye".

**Comment by ErisDS** [comment] 2022-01-20 15:59
Closing this as a duplicate of https://github.com/TryGhost/Ghost-CLI/issues/460

**Closed by ErisDS** 2022-01-20 15:59 UTC
