### ISSUE TITLE
Import JSON backup with ghost-cli

### ISSUE THREAD

**Issue by Deliaz** [TryGhost/Ghost-CLI#605] opened 2018-02-02 06:08 UTC
## This issue is a

* [ ] Bug Report
* [x] Feature Request

Hi, 
What do you think about possibility to import JSON backup using `ghost-cli`? It will be useful in case of new installations when you want to import existing content along with user credentials (in case you want to keep the same user). 
The current workflow for this seems to have one unnecessary step: creating new user right after installation. 
So, something like `ghost import <json-file>` allows us to make a quick start right after installation.

**Comment by vikaspotluri123** [comment] 2018-02-02 06:10
Seems really similar to / duplicate of #468

**Comment by acburdine** [comment] 2018-02-02 09:46
Closing as a duplicate of #468

**Closed by acburdine** 2018-02-02 09:46 UTC
