### ISSUE TITLE
Ghost container cannot create a right connection to db using docker compose.

### ISSUE THREAD

**Issue by kingcc** [TryGhost/Ghost-CLI#856] opened 2018-11-28 14:29 UTC
I would not understand why to use '%' instead of 'DB host' fields to build a connection. (#644)

When i used docker compose to link two containers(ghost and mysql) with two compose files(One network), knex migrate got wrong ip address from '%':

The ghost compose file:

```
version: '3'
services:
  blog:
    image: ghost:1-alpine
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
networks:
  default:
    external:
      name: one-network
```

The db compose file:

```
version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
networks:
  default:
    external:
      name: one-network
```

When starting ghost, some error occurs:

```sh
$ docker logs --tail=16 blog
Access denied for user 'root'@'192.168.112.9' # ip of db which right is 192.168.112.8
```

Sincerely

**Comment by acburdine** [comment] 2018-12-01 15:12
@kingcc I can't reproduce this locally unfortunately 😕The '%' wildcard in the db creation is a wildcard, so any ip address should work.

Gonna close this issue as I don't believe there's anything we can do from Ghost-CLI's perspective. I'd suggest posting on the [forum](https://forum.ghost.org) if you continue to have issues. If you have a solid reproduction case that indicates something _can_ be fixed in Ghost-CLI, then we can reopen this issue.

**Closed by acburdine** 2018-12-01 15:12 UTC

**Comment by kingcc** [comment] 2018-12-04 01:52
Hi,

Thanks for your help. I finally fixed it when i tried to reproduce this error locally.

Sincerely
